export const countryList = [
	{countryName: 'Aaland Islands', countryCode: 'AX', phoneCode: '0', isoCode: 'ALA'},
	{countryName: 'Afghanistan', countryCode: 'AF', phoneCode: '93', isoCode: 'AFG'},
	{countryName: 'Albania', countryCode: 'AL', phoneCode: '355', isoCode: 'ALB'},
	{countryName: 'American Samoa', countryCode: 'AS', phoneCode: '1', isoCode: 'ASM'},
	{countryName: 'Andorra', countryCode: 'AD', phoneCode: '376', isoCode: 'AND'},
	{countryName: 'Angola', countryCode: 'AO', phoneCode: '244', isoCode: 'AGO'},
	{countryName: 'Anguilla', countryCode: 'AI', phoneCode: '1', isoCode: 'AIA'},
	{countryName: 'Antarctica', countryCode: 'AQ', phoneCode: '672', isoCode: 'ATA'},
	{countryName: 'Antigua and Barbuda', countryCode: 'AG', phoneCode: '1', isoCode: 'ATG'},
	{countryName: 'Argentina', countryCode: 'AR', phoneCode: '54', isoCode: 'ARG'},
	{countryName: 'Armenia', countryCode: 'AM', phoneCode: '374', isoCode: 'ARM'},
	{countryName: 'Aruba', countryCode: 'AW', phoneCode: '297', isoCode: 'ABW'},
	{countryName: 'Australia', countryCode: 'AU', phoneCode: '61', isoCode: 'AUS'},
	{countryName: 'Austria', countryCode: 'AT', phoneCode: '43', isoCode: 'AUT'},
	{countryName: 'Azerbaijan', countryCode: 'AZ', phoneCode: '994', isoCode: 'AZE'},
	{countryName: 'Bahamas', countryCode: 'BS', phoneCode: '1', isoCode: 'BHS'},
	{countryName: 'Bahrain', countryCode: 'BH', phoneCode: '973', isoCode: 'BHR'},
	{countryName: 'Barbados', countryCode: 'BB', phoneCode: '1', isoCode: 'BRB'},
	{countryName: 'Belarus', countryCode: 'BY', phoneCode: '375', isoCode: 'BLR'},
	{countryName: 'Belgium', countryCode: 'BE', phoneCode: '32', isoCode: 'BEL'},
	{countryName: 'Belize', countryCode: 'BZ', phoneCode: '501', isoCode: 'BLZ'},
	{countryName: 'Benin', countryCode: 'BJ', phoneCode: '229', isoCode: 'BEN'},
	{countryName: 'Bermuda', countryCode: 'BM', phoneCode: '1', isoCode: 'BMU'},
	{countryName: 'Bhutan', countryCode: 'BT', phoneCode: '975', isoCode: 'BTN'},
	{countryName: 'Bonaire, Sint Eustatius and Saba', countryCode: 'BQ', phoneCode: '599', isoCode: 'BES'},
	{countryName: 'Bosnia and Herzegovina', countryCode: 'BA', phoneCode: '387', isoCode: 'BIH'},
	{countryName: 'Botswana', countryCode: 'BW', phoneCode: '267', isoCode: 'BWA'},
	{countryName: 'Bouvet Island', countryCode: 'BV', phoneCode: '20', isoCode: 'BVT'},
	{countryName: 'Brazil', countryCode: 'BR', phoneCode: '55', isoCode: 'BRA'},
	{countryName: 'British Indian Ocean Territory', countryCode: 'IO', phoneCode: '20', isoCode: 'IOT'},
	{countryName: 'Brunei Darussalam', countryCode: 'BN', phoneCode: '673', isoCode: 'BRN'},
	{countryName: 'Bulgaria', countryCode: 'BG', phoneCode: '359', isoCode: 'BGR'},
	{countryName: 'Burkina Faso', countryCode: 'BF', phoneCode: '226', isoCode: 'BFA'},
	{countryName: 'Burundi', countryCode: 'BI', phoneCode: '257', isoCode: 'BDI'},
	{countryName: 'Cambodia', countryCode: 'KH', phoneCode: '855', isoCode: 'KHM'},
	{countryName: 'Cameroon', countryCode: 'CM', phoneCode: '237', isoCode: 'CMR'},
	{countryName: 'Canada', countryCode: 'CA', phoneCode: '1', isoCode: 'CAN'},
	{countryName: 'Canary Islands', countryCode: 'IC', phoneCode: '34', isoCode: 'ICA'},
	{countryName: 'Cape Verde', countryCode: 'CV', phoneCode: '238', isoCode: 'CPV'},
	{countryName: 'Cayman Islands', countryCode: 'KY', phoneCode: '1', isoCode: 'CYM'},
	{countryName: 'Central African Republic', countryCode: 'CF', phoneCode: '236', isoCode: 'CAF'},
	{countryName: 'Chad', countryCode: 'TD', phoneCode: '235', isoCode: 'TCD'},
	{countryName: 'Chile', countryCode: 'CL', phoneCode: '56', isoCode: 'CHL'},
	{countryName: 'Christmas Island', countryCode: 'CX', phoneCode: '61', isoCode: 'CXR'},
	{countryName: 'Cocos (Keeling) Islands', countryCode: 'CC', phoneCode: '61', isoCode: 'CCK'},
	{countryName: 'Colombia', countryCode: 'CO', phoneCode: '57', isoCode: 'COL'},
	{countryName: 'Comoros', countryCode: 'KM', phoneCode: '269', isoCode: 'COM'},
	{countryName: 'Congo', countryCode: 'CG', phoneCode: '242', isoCode: 'COG'},
	{countryName: 'Cook Islands', countryCode: 'CK', phoneCode: '682', isoCode: 'COK'},
	{countryName: 'Costa Rica', countryCode: 'CR', phoneCode: '506', isoCode: 'CRI'},
	{countryName: 'Cote D&#39;Ivoire', countryCode: 'CI', phoneCode: '225', isoCode: 'CIV'},
	{countryName: 'Croatia', countryCode: 'HR', phoneCode: '385', isoCode: 'HRV'},
	{countryName: 'Curacao', countryCode: 'CW', phoneCode: '599', isoCode: 'CUW'},
	{countryName: 'Cyprus', countryCode: 'CY', phoneCode: '357', isoCode: 'CYP'},
	{countryName: 'Czech Republic', countryCode: 'CZ', phoneCode: '420', isoCode: 'CZE'},
	{countryName: 'Democratic Republic of Congo', countryCode: 'CD', phoneCode: '243', isoCode: 'COD'},
	{countryName: 'Denmark', countryCode: 'DK', phoneCode: '45', isoCode: 'DNK'},
	{countryName: 'Djibouti', countryCode: 'DJ', phoneCode: '253', isoCode: 'DJI'},
	{countryName: 'Dominica', countryCode: 'DM', phoneCode: '1', isoCode: 'DMA'},
	{countryName: 'Dominican Republic', countryCode: 'DO', phoneCode: '1', isoCode: 'DOM'},
	{countryName: 'East Timor', countryCode: 'TL', phoneCode: '670', isoCode: 'TLS'},
	{countryName: 'Egypt', countryCode: 'EG', phoneCode: '20', isoCode: 'EGY'},
	{countryName: 'El Salvador', countryCode: 'SV', phoneCode: '503', isoCode: 'SLV'},
	{countryName: 'Equatorial Guinea', countryCode: 'GQ', phoneCode: '240', isoCode: 'GNQ'},
	{countryName: 'Eritrea', countryCode: 'ER', phoneCode: '291', isoCode: 'ERI'},
	{countryName: 'Estonia', countryCode: 'EE', phoneCode: '372', isoCode: 'EST'},
	{countryName: 'Ethiopia', countryCode: 'ET', phoneCode: '251', isoCode: 'ETH'},
	{countryName: 'Falkland Islands (Malvinas)', countryCode: 'FK', phoneCode: '500', isoCode: 'FLK'},
	{countryName: 'Faroe Islands', countryCode: 'FO', phoneCode: '298', isoCode: 'FRO'},
	{countryName: 'Fiji', countryCode: 'FJ', phoneCode: '679', isoCode: 'FJI'},
	{countryName: 'Finland', countryCode: 'FI', phoneCode: '358', isoCode: 'FIN'},
	{countryName: 'France, Metropolitan', countryCode: 'FR', phoneCode: '0', isoCode: 'FRA'},
	{countryName: 'French Guiana', countryCode: 'GF', phoneCode: '224', isoCode: 'GUF'},
	{countryName: 'French Polynesia', countryCode: 'PF', phoneCode: '689', isoCode: 'PYF'},
	{countryName: 'French Southern Territories', countryCode: 'TF', phoneCode: '262', isoCode: 'ATF'},
	{countryName: 'FYROM', countryCode: 'MK', phoneCode: '389', isoCode: 'MKD'},
	{countryName: 'Gabon', countryCode: 'GA', phoneCode: '241', isoCode: 'GAB'},
	{countryName: 'Gambia', countryCode: 'GM', phoneCode: '220', isoCode: 'GMB'},
	{countryName: 'Georgia', countryCode: 'GE', phoneCode: '995', isoCode: 'GEO'},
	{countryName: 'Germany', countryCode: 'DE', phoneCode: '49', isoCode: 'DEU'},
	{countryName: 'Ghana', countryCode: 'GH', phoneCode: '233', isoCode: 'GHA'},
	{countryName: 'Gibraltar', countryCode: 'GI', phoneCode: '350', isoCode: 'GIB'},
	{countryName: 'Greece', countryCode: 'GR', phoneCode: '30', isoCode: 'GRC'},
	{countryName: 'Greenland', countryCode: 'GL', phoneCode: '299', isoCode: 'GRL'},
	{countryName: 'Grenada', countryCode: 'GD', phoneCode: '1', isoCode: 'GRD'},
	{countryName: 'Guadeloupe', countryCode: 'GP', phoneCode: '20', isoCode: 'GLP'},
	{countryName: 'Guam', countryCode: 'GU', phoneCode: '1', isoCode: 'GUM'},
	{countryName: 'Guatemala', countryCode: 'GT', phoneCode: '502', isoCode: 'GTM'},
	{countryName: 'Guernsey', countryCode: 'GG', phoneCode: '20', isoCode: 'GGY'},
	{countryName: 'Guinea', countryCode: 'GN', phoneCode: '224', isoCode: 'GIN'},
	{countryName: 'Guinea-Bissau', countryCode: 'GW', phoneCode: '245', isoCode: 'GNB'},
	{countryName: 'Guyana', countryCode: 'GY', phoneCode: '592', isoCode: 'GUY'},
	{countryName: 'Haiti', countryCode: 'HT', phoneCode: '509', isoCode: 'HTI'},
	{countryName: 'Heard and Mc Donald Islands', countryCode: 'HM', phoneCode: '0', isoCode: 'HMD'},
	{countryName: 'Honduras', countryCode: 'HN', phoneCode: '504', isoCode: 'HND'},
	{countryName: 'Hong Kong', countryCode: 'HK', phoneCode: '852', isoCode: 'HKG'},
	{countryName: 'Hungary', countryCode: 'HU', phoneCode: '36', isoCode: 'HUN'},
	{countryName: 'Iceland', countryCode: 'IS', phoneCode: '354', isoCode: 'ISL'},
	{countryName: 'India', countryCode: 'IN', phoneCode: '91', isoCode: 'IND'},
	{countryName: 'Indonesia', countryCode: 'ID', phoneCode: '62', isoCode: 'IDN'},
	{countryName: 'Iraq', countryCode: 'IQ', phoneCode: '964', isoCode: 'IRQ'},
	{countryName: 'Ireland', countryCode: 'IE', phoneCode: '353', isoCode: 'IRL'},
	{countryName: 'Israel', countryCode: 'IL', phoneCode: '972', isoCode: 'ISR'},
	{countryName: 'Italy', countryCode: 'IT', phoneCode: '39', isoCode: 'ITA'},
	{countryName: 'Jamaica', countryCode: 'JM', phoneCode: '1', isoCode: 'JAM'},
	{countryName: 'Japan', countryCode: 'JP', phoneCode: '81', isoCode: 'JPN'},
	{countryName: 'Jersey', countryCode: 'JE', phoneCode: '20', isoCode: 'JEY'},
	{countryName: 'Jordan', countryCode: 'JO', phoneCode: '962', isoCode: 'JOR'},
	{countryName: 'Kazakhstan', countryCode: 'KZ', phoneCode: '7', isoCode: 'KAZ'},
	{countryName: 'Kenya', countryCode: 'KE', phoneCode: '254', isoCode: 'KEN'},
	{countryName: 'Kiribati', countryCode: 'KI', phoneCode: '686', isoCode: 'KIR'},
	{countryName: 'Korea, Republic of', countryCode: 'KR', phoneCode: '82', isoCode: 'KOR'},
	{countryName: 'Kosovo', countryCode: 'XK', phoneCode: '383', isoCode: 'XKS'},
	{countryName: 'Kuwait', countryCode: 'KW', phoneCode: '965', isoCode: 'KWT'},
	{countryName: 'Lao People&#39;s Democratic Republic', countryCode: 'LA', phoneCode: '856', isoCode: 'LAO'},
	{countryName: 'Latvia', countryCode: 'LV', phoneCode: '371', isoCode: 'LVA'},
	{countryName: 'Lebanon', countryCode: 'LB', phoneCode: '961', isoCode: 'LBN'},
	{countryName: 'Lesotho', countryCode: 'LS', phoneCode: '266', isoCode: 'LSO'},
	{countryName: 'Liberia', countryCode: 'LR', phoneCode: '231', isoCode: 'LBR'},
	{countryName: 'Libyan Arab Jamahiriya', countryCode: 'LY', phoneCode: '218', isoCode: 'LBY'},
	{countryName: 'Liechtenstein', countryCode: 'LI', phoneCode: '423', isoCode: 'LIE'},
	{countryName: 'Lithuania', countryCode: 'LT', phoneCode: '370', isoCode: 'LTU'},
	{countryName: 'Luxembourg', countryCode: 'LU', phoneCode: '352', isoCode: 'LUX'},
	{countryName: 'Macau', countryCode: 'MO', phoneCode: '853', isoCode: 'MAC'},
	{countryName: 'Madagascar', countryCode: 'MG', phoneCode: '261', isoCode: 'MDG'},
	{countryName: 'Malawi', countryCode: 'MW', phoneCode: '265', isoCode: 'MWI'},
	{countryName: 'Malaysia', countryCode: 'MY', phoneCode: '60', isoCode: 'MYS'},
	{countryName: 'Maldives', countryCode: 'MV', phoneCode: '960', isoCode: 'MDV'},
	{countryName: 'Mali', countryCode: 'ML', phoneCode: '223', isoCode: 'MLI'},
	{countryName: 'Malta', countryCode: 'MT', phoneCode: '356', isoCode: 'MLT'},
	{countryName: 'Marshall Islands', countryCode: 'MH', phoneCode: '692', isoCode: 'MHL'},
	{countryName: 'Martinique', countryCode: 'MQ', phoneCode: '222', isoCode: 'MTQ'},
	{countryName: 'Mauritania', countryCode: 'MR', phoneCode: '222', isoCode: 'MRT'},
	{countryName: 'Mauritius', countryCode: 'MU', phoneCode: '230', isoCode: 'MUS'},
	{countryName: 'Mayotte', countryCode: 'YT', phoneCode: '626', isoCode: 'MYT'},
	{countryName: 'Mexico', countryCode: 'MX', phoneCode: '52', isoCode: 'MEX'},
	{countryName: 'Micronesia, Federated States of', countryCode: 'FM', phoneCode: '691', isoCode: 'FSM'},
	{countryName: 'Moldova, Republic of', countryCode: 'MD', phoneCode: '373', isoCode: 'MDA'},
	{countryName: 'Monaco', countryCode: 'MC', phoneCode: '377', isoCode: 'MCO'},
	{countryName: 'Mongolia', countryCode: 'MN', phoneCode: '976', isoCode: 'MNG'},
	{countryName: 'Montenegro', countryCode: 'ME', phoneCode: '382', isoCode: 'MNE'},
	{countryName: 'Montserrat', countryCode: 'MS', phoneCode: '1', isoCode: 'MSR'},
	{countryName: 'Morocco', countryCode: 'MA', phoneCode: '212', isoCode: 'MAR'},
	{countryName: 'Mozambique', countryCode: 'MZ', phoneCode: '258', isoCode: 'MOZ'},
	{countryName: 'Myanmar', countryCode: 'MM', phoneCode: '95', isoCode: 'MMR'},
	{countryName: 'Nauru', countryCode: 'NR', phoneCode: '674', isoCode: 'NRU'},
	{countryName: 'Netherlands', countryCode: 'NL', phoneCode: '31', isoCode: 'NLD'},
	{countryName: 'Netherlands Antilles', countryCode: 'AN', phoneCode: '599', isoCode: 'ANT'},
	{countryName: 'New Caledonia', countryCode: 'NC', phoneCode: '687', isoCode: 'NCL'},
	{countryName: 'New Zealand', countryCode: 'NZ', phoneCode: '64', isoCode: 'NZL'},
	{countryName: 'Nicaragua', countryCode: 'NI', phoneCode: '505', isoCode: 'NIC'},
	{countryName: 'Niger', countryCode: 'NE', phoneCode: '227', isoCode: 'NER'},
	{countryName: 'Nigeria', countryCode: 'NG', phoneCode: '234', isoCode: 'NGA'},
	{countryName: 'Niue', countryCode: 'NU', phoneCode: '683', isoCode: 'NIU'},
	{countryName: 'Norfolk Island', countryCode: 'NF', phoneCode: '672', isoCode: 'NFK'},
	{countryName: 'Northern Mariana Islands', countryCode: 'MP', phoneCode: '1', isoCode: 'MNP'},
	{countryName: 'Norway', countryCode: 'NO', phoneCode: '47', isoCode: 'NOR'},
	{countryName: 'Oman', countryCode: 'OM', phoneCode: '968', isoCode: 'OMN'},
	{countryName: 'Pakistan', countryCode: 'PK', phoneCode: '92', isoCode: 'PAK'},
	{countryName: 'Palau', countryCode: 'PW', phoneCode: '680', isoCode: 'PLW'},
	{countryName: 'Palestinian Territory, Occupied', countryCode: 'PS', phoneCode: '970', isoCode: 'PSE'},
	{countryName: 'Panama', countryCode: 'PA', phoneCode: '507', isoCode: 'PAN'},
	{countryName: 'Papua New Guinea', countryCode: 'PG', phoneCode: '675', isoCode: 'PNG'},
	{countryName: 'Paraguay', countryCode: 'PY', phoneCode: '595', isoCode: 'PRY'},
	{countryName: 'Peru', countryCode: 'PE', phoneCode: '51', isoCode: 'PER'},
	{countryName: 'Philippines', countryCode: 'PH', phoneCode: '63', isoCode: 'PHL'},
	{countryName: 'Pitcairn', countryCode: 'PN', phoneCode: '870', isoCode: 'PCN'},
	{countryName: 'Poland', countryCode: 'PL', phoneCode: '48', isoCode: 'POL'},
	{countryName: 'Portugal', countryCode: 'PT', phoneCode: '351', isoCode: 'PRT'},
	{countryName: 'Puerto Rico', countryCode: 'PR', phoneCode: '1', isoCode: 'PRI'},
	{countryName: 'Qatar', countryCode: 'QA', phoneCode: '974', isoCode: 'QAT'},
	{countryName: 'Reunion', countryCode: 'RE', phoneCode: '20', isoCode: 'REU'},
	{countryName: 'Romania', countryCode: 'RO', phoneCode: '40', isoCode: 'ROM'},
	{countryName: 'Russian Federation', countryCode: 'RU', phoneCode: '7', isoCode: 'RUS'},
	{countryName: 'Rwanda', countryCode: 'RW', phoneCode: '250', isoCode: 'RWA'},
	{countryName: 'Saint Kitts and Nevis', countryCode: 'KN', phoneCode: '1', isoCode: 'KNA'},
	{countryName: 'Saint Lucia', countryCode: 'LC', phoneCode: '1', isoCode: 'LCA'},
	{countryName: 'Saint Vincent and the Grenadines', countryCode: 'VC', phoneCode: '1', isoCode: 'VCT'},
	{countryName: 'Samoa', countryCode: 'WS', phoneCode: '685', isoCode: 'WSM'},
	{countryName: 'San Marino', countryCode: 'SM', phoneCode: '378', isoCode: 'SMR'},
	{countryName: 'Sao Tome and Principe', countryCode: 'ST', phoneCode: '239', isoCode: 'STP'},
	{countryName: 'Saudi Arabia', countryCode: 'SA', phoneCode: '966', isoCode: 'SAU'},
	{countryName: 'Senegal', countryCode: 'SN', phoneCode: '221', isoCode: 'SEN'},
	{countryName: 'Serbia', countryCode: 'RS', phoneCode: '381', isoCode: 'SRB'},
	{countryName: 'Seychelles', countryCode: 'SC', phoneCode: '248', isoCode: 'SYC'},
	{countryName: 'Sierra Leone', countryCode: 'SL', phoneCode: '232', isoCode: 'SLE'},
	{countryName: 'Singapore', countryCode: 'SG', phoneCode: '65', isoCode: 'SGP'},
	{countryName: 'Slovak Republic', countryCode: 'SK', phoneCode: '421', isoCode: 'SVK'},
	{countryName: 'Slovenia', countryCode: 'SI', phoneCode: '386', isoCode: 'SVN'},
	{countryName: 'Solomon Islands', countryCode: 'SB', phoneCode: '677', isoCode: 'SLB'},
	{countryName: 'Somalia', countryCode: 'SO', phoneCode: '252', isoCode: 'SOM'},
	{countryName: 'South Africa', countryCode: 'ZA', phoneCode: '27', isoCode: 'ZAF'},
	{countryName: 'South Georgia &amp; South Sandwich Islands', countryCode: 'GS', phoneCode: '500', isoCode: 'SGS'},
	{countryName: 'Spain', countryCode: 'ES', phoneCode: '34', isoCode: 'ESP'},
	{countryName: 'Sri Lanka', countryCode: 'LK', phoneCode: '94', isoCode: 'LKA'},
	{countryName: 'St. Barthelemy', countryCode: 'BL', phoneCode: '590', isoCode: 'BLM'},
	{countryName: 'St. Helena', countryCode: 'SH', phoneCode: '290', isoCode: 'SHN'},
	{countryName: 'St. Martin (French part)', countryCode: 'MF', phoneCode: '590', isoCode: 'MAF'},
	{countryName: 'St. Pierre and Miquelon', countryCode: 'PM', phoneCode: '508', isoCode: 'SPM'},
	{countryName: 'Suriname', countryCode: 'SR', phoneCode: '597', isoCode: 'SUR'},
	{countryName: 'Svalbard and Jan Mayen Islands', countryCode: 'SJ', phoneCode: '47', isoCode: 'SJM'},
	{countryName: 'Swaziland', countryCode: 'SZ', phoneCode: '268', isoCode: 'SWZ'},
	{countryName: 'Sweden', countryCode: 'SE', phoneCode: '46', isoCode: 'SWE'},
	{countryName: 'Switzerland', countryCode: 'CH', phoneCode: '41', isoCode: 'CHE'},
	{countryName: 'Taiwan', countryCode: 'TW', phoneCode: '886', isoCode: 'TWN'},
	{countryName: 'Tajikistan', countryCode: 'TJ', phoneCode: '992', isoCode: 'TJK'},
	{countryName: 'Tanzania, United Republic of', countryCode: 'TZ', phoneCode: '255', isoCode: 'TZA'},
	{countryName: 'Thailand', countryCode: 'TH', phoneCode: '66', isoCode: 'THA'},
	{countryName: 'Togo', countryCode: 'TG', phoneCode: '228', isoCode: 'TGO'},
	{countryName: 'Tokelau', countryCode: 'TK', phoneCode: '690', isoCode: 'TKL'},
	{countryName: 'Tonga', countryCode: 'TO', phoneCode: '676', isoCode: 'TON'},
	{countryName: 'Trinidad and Tobago', countryCode: 'TT', phoneCode: '1', isoCode: 'TTO'},
	{countryName: 'Tunisia', countryCode: 'TN', phoneCode: '216', isoCode: 'TUN'},
	{countryName: 'Turkey', countryCode: 'TR', phoneCode: '90', isoCode: 'TUR'},
	{countryName: 'Turkmenistan', countryCode: 'TM', phoneCode: '993', isoCode: 'TKM'},
	{countryName: 'Turks and Caicos Islands', countryCode: 'TC', phoneCode: '1', isoCode: 'TCA'},
	{countryName: 'Tuvalu', countryCode: 'TV', phoneCode: '688', isoCode: 'TUV'},
	{countryName: 'Uganda', countryCode: 'UG', phoneCode: '256', isoCode: 'UGA'},
	{countryName: 'Ukraine', countryCode: 'UA', phoneCode: '380', isoCode: 'UKR'},
	{countryName: 'United Arab Emirates', countryCode: 'AE', phoneCode: '971', isoCode: 'ARE'},
	{countryName: 'United Kingdom', countryCode: 'GB', phoneCode: '44', isoCode: 'GBR'},
	{countryName: 'United States Minor Outlying Islands', countryCode: 'UM', phoneCode: '0', isoCode: 'UMI'},
	{countryName: 'Uruguay', countryCode: 'UY', phoneCode: '598', isoCode: 'URY'},
	{countryName: 'Uzbekistan', countryCode: 'UZ', phoneCode: '998', isoCode: 'UZB'},
	{countryName: 'Vanuatu', countryCode: 'VU', phoneCode: '678', isoCode: 'VUT'},
	{countryName: 'Vatican City State (Holy See)', countryCode: 'VA', phoneCode: '379', isoCode: 'VAT'},
	{countryName: 'Venezuela', countryCode: 'VE', phoneCode: '58', isoCode: 'VEN'},
	{countryName: 'Viet Nam', countryCode: 'VN', phoneCode: '84', isoCode: 'VNM'},
	{countryName: 'Virgin Islands (British)', countryCode: 'VG', phoneCode: '1284', isoCode: 'VGB'},
	{countryName: 'Virgin Islands (U.S.)', countryCode: 'VI', phoneCode: '1340', isoCode: 'VIR'},
	{countryName: 'Wallis and Futuna Islands', countryCode: 'WF', phoneCode: '681', isoCode: 'WLF'},
	{countryName: 'Western Sahara', countryCode: 'EH', phoneCode: '20', isoCode: 'ESH'},
	{countryName: 'Yemen', countryCode: 'YE', phoneCode: '967', isoCode: 'YEM'},
	{countryName: 'Zambia', countryCode: 'ZM', phoneCode: '260', isoCode: 'ZMB'},
	{countryName: 'Zimbabwe', countryCode: 'ZW', phoneCode: '263', isoCode: 'ZWE'}
]
