export const cityList = [
  { "name": "Caloocan", "stateCode": "MM", "city": true },
  { "name": "Las Piñas", "stateCode": "MM", "city": true },
  { "name": "Makati", "stateCode": "MM", "city": true },
  { "name": "Malabon", "stateCode": "MM", "city": true },
  { "name": "Mandaluyong", "stateCode": "MM", "city": true },
  { "name": "Manila", "stateCode": "MM", "city": true },
  { "name": "Marikina", "stateCode": "MM", "city": true },
  { "name": "Muntinlupa", "stateCode": "MM", "city": true },
  { "name": "Navotas", "stateCode": "MM", "city": true },
  { "name": "Parañaque", "stateCode": "MM", "city": true },
  { "name": "Pasay", "stateCode": "MM", "city": true },
  { "name": "Pasig", "stateCode": "MM", "city": true },
  { "name": "Pateros", "stateCode": "MM" },
  { "name": "Quezon", "stateCode": "MM", "city": true },
  { "name": "San Juan", "stateCode": "MM", "city": true },
  { "name": "Taguig", "stateCode": "MM", "city": true },
  { "name": "Valenzuela", "stateCode": "MM", "city": true },

  { "name": "Bangued", "stateCode": "ABR" },
  { "name": "Boliney", "stateCode": "ABR" },
  { "name": "Bucay", "stateCode": "ABR" },
  { "name": "Bucloc", "stateCode": "ABR" },
  { "name": "Daguioman", "stateCode": "ABR" },
  { "name": "Danglas", "stateCode": "ABR" },
  { "name": "Dolores", "stateCode": "ABR" },
  { "name": "La Paz", "stateCode": "ABR" },
  { "name": "Lacub", "stateCode": "ABR" },
  { "name": "Lagangilang", "stateCode": "ABR" },
  { "name": "Lagayan", "stateCode": "ABR" },
  { "name": "Langiden", "stateCode": "ABR" },
  { "name": "Licuan-Baay", "stateCode": "ABR" },
  { "name": "Luba", "stateCode": "ABR" },
  { "name": "Malibcong", "stateCode": "ABR" },
  { "name": "Manabo", "stateCode": "ABR" },
  { "name": "Peñarrubia", "stateCode": "ABR" },
  { "name": "Pidigan", "stateCode": "ABR" },
  { "name": "Pilar", "stateCode": "ABR" },
  { "name": "Sallapadan", "stateCode": "ABR" },
  { "name": "San Isidro", "stateCode": "ABR" },
  { "name": "San Juan", "stateCode": "ABR" },
  { "name": "San Quintin", "stateCode": "ABR" },
  { "name": "Tayum", "stateCode": "ABR" },
  { "name": "Tineg", "stateCode": "ABR" },
  { "name": "Tubo", "stateCode": "ABR" },
  { "name": "Villaviciosa", "stateCode": "ABR" },

  { "name": "Calanasan", "stateCode": "APA" },
  { "name": "Conner", "stateCode": "APA" },
  { "name": "Flora", "stateCode": "APA" },
  { "name": "Kabugao", "stateCode": "APA" },
  { "name": "Luna", "stateCode": "APA" },
  { "name": "Pudtol", "stateCode": "APA" },
  { "name": "Santa Marcela", "stateCode": "APA" },

  { "name": "Atok", "stateCode": "BEN" },
  { "name": "Baguio", "stateCode": "BEN", "city": true },
  { "name": "Bakun", "stateCode": "BEN" },
  { "name": "Bokod", "stateCode": "BEN" },
  { "name": "Buguias", "stateCode": "BEN" },
  { "name": "Itogon", "stateCode": "BEN" },
  { "name": "Kabayan", "stateCode": "BEN" },
  { "name": "Kapangan", "stateCode": "BEN" },
  { "name": "Kibungan", "stateCode": "BEN" },
  { "name": "La Trinidad", "stateCode": "BEN" },
  { "name": "Mankayan", "stateCode": "BEN" },
  { "name": "Sablan", "stateCode": "BEN" },
  { "name": "Tuba", "stateCode": "BEN" },
  { "name": "Tublay", "stateCode": "BEN" },

  { "name": "Aguinaldo", "stateCode": "IFU" },
  { "name": "Alfonso Lista", "stateCode": "IFU" },
  { "name": "Asipulo", "stateCode": "IFU" },
  { "name": "Banaue", "stateCode": "IFU" },
  { "name": "Hingyon", "stateCode": "IFU" },
  { "name": "Hungduan", "stateCode": "IFU" },
  { "name": "Kiangan", "stateCode": "IFU" },
  { "name": "Lagawe", "stateCode": "IFU" },
  { "name": "Lamut", "stateCode": "IFU" },
  { "name": "Mayoyao", "stateCode": "IFU" },
  { "name": "Tinoc", "stateCode": "IFU" },

  { "name": "Balbalan", "stateCode": "KAL" },
  { "name": "Lubuagan", "stateCode": "KAL" },
  { "name": "Pasil", "stateCode": "KAL" },
  { "name": "Pinukpuk", "stateCode": "KAL" },
  { "name": "Rizal", "stateCode": "KAL" },
  { "name": "Tabuk", "stateCode": "KAL", "city": true },
  { "name": "Tanudan", "stateCode": "KAL" },
  { "name": "Tinglayan", "stateCode": "KAL" },

  { "name": "Barlig", "stateCode": "MOU" },
  { "name": "Bauko", "stateCode": "MOU" },
  { "name": "Besao", "stateCode": "MOU" },
  { "name": "Bontoc", "stateCode": "MOU" },
  { "name": "Natonin", "stateCode": "MOU" },
  { "name": "Paracelis", "stateCode": "MOU" },
  { "name": "Sabangan", "stateCode": "MOU" },
  { "name": "Sadanga", "stateCode": "MOU" },
  { "name": "Sagada", "stateCode": "MOU" },
  { "name": "Tadian", "stateCode": "MOU" },

  { "name": "Adams", "stateCode": "ILN" },
  { "name": "Bacarra", "stateCode": "ILN" },
  { "name": "Badoc", "stateCode": "ILN" },
  { "name": "Bangui", "stateCode": "ILN" },
  { "name": "Banna", "stateCode": "ILN" },
  { "name": "Batac", "stateCode": "ILN", "city": true },
  { "name": "Burgos", "stateCode": "ILN" },
  { "name": "Carasi", "stateCode": "ILN" },
  { "name": "Currimao", "stateCode": "ILN" },
  { "name": "Dingras", "stateCode": "ILN" },
  { "name": "Dumalneg", "stateCode": "ILN" },
  { "name": "Laoag", "stateCode": "ILN", "city": true },
  { "name": "Marcos", "stateCode": "ILN" },
  { "name": "Nueva Era", "stateCode": "ILN" },
  { "name": "Pagudpud", "stateCode": "ILN" },
  { "name": "Paoay", "stateCode": "ILN" },
  { "name": "Pasuquin", "stateCode": "ILN" },
  { "name": "Piddig", "stateCode": "ILN" },
  { "name": "Pinili", "stateCode": "ILN" },
  { "name": "San Nicolas", "stateCode": "ILN" },
  { "name": "Sarrat", "stateCode": "ILN" },
  { "name": "Solsona", "stateCode": "ILN" },
  { "name": "Vintar", "stateCode": "ILN" },

  { "name": "Alilem", "stateCode": "ILS" },
  { "name": "Banayoyo", "stateCode": "ILS" },
  { "name": "Bantay", "stateCode": "ILS" },
  { "name": "Burgos", "stateCode": "ILS" },
  { "name": "Cabugao", "stateCode": "ILS" },
  { "name": "Candon", "stateCode": "ILS", "city": true },
  { "name": "Caoayan", "stateCode": "ILS" },
  { "name": "Cervantes", "stateCode": "ILS" },
  { "name": "Galimuyod", "stateCode": "ILS" },
  { "name": "Gregorio Del Pilar", "stateCode": "ILS" },
  { "name": "Lidlidda", "stateCode": "ILS" },
  { "name": "Magsingal", "stateCode": "ILS" },
  { "name": "Nagbukel", "stateCode": "ILS" },
  { "name": "Narvacan", "stateCode": "ILS" },
  { "name": "Quirino", "stateCode": "ILS" },
  { "name": "Salcedo", "stateCode": "ILS" },
  { "name": "San Emilio", "stateCode": "ILS" },
  { "name": "San Esteban", "stateCode": "ILS" },
  { "name": "San Ildefonso", "stateCode": "ILS" },
  { "name": "San Juan", "stateCode": "ILS" },
  { "name": "San Vicente", "stateCode": "ILS" },
  { "name": "Santa", "stateCode": "ILS" },
  { "name": "Santa Catalina", "stateCode": "ILS" },
  { "name": "Santa Cruz", "stateCode": "ILS" },
  { "name": "Santa Lucia", "stateCode": "ILS" },
  { "name": "Santa Maria", "stateCode": "ILS" },
  { "name": "Santiago", "stateCode": "ILS" },
  { "name": "Santo Domingo", "stateCode": "ILS" },
  { "name": "Sigay", "stateCode": "ILS" },
  { "name": "Sinait", "stateCode": "ILS" },
  { "name": "Sugpon", "stateCode": "ILS" },
  { "name": "Suyo", "stateCode": "ILS" },
  { "name": "Tagudin", "stateCode": "ILS" },
  { "name": "Vigan", "stateCode": "ILS", "city": true },

  { "name": "Agoo", "stateCode": "LUN" },
  { "name": "Aringay", "stateCode": "LUN" },
  { "name": "Bacnotan", "stateCode": "LUN" },
  { "name": "Bagulin", "stateCode": "LUN" },
  { "name": "Balaoan", "stateCode": "LUN" },
  { "name": "Bangar", "stateCode": "LUN" },
  { "name": "Bauang", "stateCode": "LUN" },
  { "name": "Burgos", "stateCode": "LUN" },
  { "name": "Caba", "stateCode": "LUN" },
  { "name": "Luna", "stateCode": "LUN" },
  { "name": "Naguilian", "stateCode": "LUN" },
  { "name": "Pugo", "stateCode": "LUN" },
  { "name": "Rosario", "stateCode": "LUN" },
  { "name": "San Fernando", "stateCode": "LUN", "city": true },
  { "name": "San Gabriel", "stateCode": "LUN" },
  { "name": "San Juan", "stateCode": "LUN" },
  { "name": "Santo Tomas", "stateCode": "LUN" },
  { "name": "Santol", "stateCode": "LUN" },
  { "name": "Sudipen", "stateCode": "LUN" },
  { "name": "Tubao", "stateCode": "LUN" },

  { "name": "Agno", "stateCode": "PAN" },
  { "name": "Aguilar", "stateCode": "PAN" },
  { "name": "Alaminos", "stateCode": "PAN", "city": true },
  { "name": "Alcala", "stateCode": "PAN" },
  { "name": "Anda", "stateCode": "PAN" },
  { "name": "Asingan", "stateCode": "PAN" },
  { "name": "Balungao", "stateCode": "PAN" },
  { "name": "Bani", "stateCode": "PAN" },
  { "name": "Basista", "stateCode": "PAN" },
  { "name": "Bautista", "stateCode": "PAN" },
  { "name": "Bayambang", "stateCode": "PAN" },
  { "name": "Binalonan", "stateCode": "PAN" },
  { "name": "Binmaley", "stateCode": "PAN" },
  { "name": "Bolinao", "stateCode": "PAN" },
  { "name": "Bugallon", "stateCode": "PAN" },
  { "name": "Burgos", "stateCode": "PAN" },
  { "name": "Calasiao", "stateCode": "PAN" },
  { "name": "Dagupan", "stateCode": "PAN", "city": true },
  { "name": "Dasol", "stateCode": "PAN" },
  { "name": "Infanta", "stateCode": "PAN" },
  { "name": "Labrador", "stateCode": "PAN" },
  { "name": "Laoac", "stateCode": "PAN" },
  { "name": "Lingayen", "stateCode": "PAN" },
  { "name": "Mabini", "stateCode": "PAN" },
  { "name": "Malasiqui", "stateCode": "PAN" },
  { "name": "Manaoag", "stateCode": "PAN" },
  { "name": "Mangaldan", "stateCode": "PAN" },
  { "name": "Mangatarem", "stateCode": "PAN" },
  { "name": "Mapandan", "stateCode": "PAN" },
  { "name": "Natividad", "stateCode": "PAN" },
  { "name": "Pozzorubio", "stateCode": "PAN" },
  { "name": "Rosales", "stateCode": "PAN" },
  { "name": "San Carlos", "stateCode": "PAN", "city": true },
  { "name": "San Fabian", "stateCode": "PAN" },
  { "name": "San Jacinto", "stateCode": "PAN" },
  { "name": "San Manuel", "stateCode": "PAN" },
  { "name": "San Nicolas", "stateCode": "PAN" },
  { "name": "San Quintin", "stateCode": "PAN" },
  { "name": "Santa Barbara", "stateCode": "PAN" },
  { "name": "Santa Maria", "stateCode": "PAN" },
  { "name": "Santo Tomas", "stateCode": "PAN" },
  { "name": "Sison", "stateCode": "PAN" },
  { "name": "Sual", "stateCode": "PAN" },
  { "name": "Tayug", "stateCode": "PAN" },
  { "name": "Umingan", "stateCode": "PAN" },
  { "name": "Urdaneta", "stateCode": "PAN", "city": true },
  { "name": "Urbiztondo", "stateCode": "PAN" },
  { "name": "Villasis", "stateCode": "PAN" },

  { "name": "Basco", "stateCode": "BTN" },
  { "name": "Itbayat", "stateCode": "BTN" },
  { "name": "Ivana", "stateCode": "BTN" },
  { "name": "Mahatao", "stateCode": "BTN" },
  { "name": "Sabtang", "stateCode": "BTN" },
  { "name": "Uyugan", "stateCode": "BTN" },

  { "name": "Abulug", "stateCode": "CAG" },
  { "name": "Alcala", "stateCode": "CAG" },
  { "name": "Allacapan", "stateCode": "CAG" },
  { "name": "Amulung", "stateCode": "CAG" },
  { "name": "Aparri", "stateCode": "CAG" },
  { "name": "Baggao", "stateCode": "CAG" },
  { "name": "Ballesteros", "stateCode": "CAG" },
  { "name": "Buguey", "stateCode": "CAG" },
  { "name": "Calayan", "stateCode": "CAG" },
  { "name": "Camalaniugan", "stateCode": "CAG" },
  { "name": "Claveria", "stateCode": "CAG" },
  { "name": "Enrile", "stateCode": "CAG" },
  { "name": "Gattaran", "stateCode": "CAG" },
  { "name": "Gonzaga", "stateCode": "CAG" },
  { "name": "Iguig", "stateCode": "CAG" },
  { "name": "Lal-lo", "stateCode": "CAG" },
  { "name": "Lasam", "stateCode": "CAG" },
  { "name": "Pamplona", "stateCode": "CAG" },
  { "name": "Peñablanca", "stateCode": "CAG" },
  { "name": "Piat", "stateCode": "CAG" },
  { "name": "Rizal", "stateCode": "CAG" },
  { "name": "Sanchez-Mira", "stateCode": "CAG" },
  { "name": "Santa Ana", "stateCode": "CAG" },
  { "name": "Santa Praxedes", "stateCode": "CAG" },
  { "name": "Santa Teresita", "stateCode": "CAG" },
  { "name": "Santo Niño", "stateCode": "CAG" },
  { "name": "Solana", "stateCode": "CAG" },
  { "name": "Tuao", "stateCode": "CAG" },
  { "name": "Tuguegarao", "stateCode": "CAG", "city": true },

  { "name": "Alicia", "stateCode": "ISA" },
  { "name": "Angadanan", "stateCode": "ISA" },
  { "name": "Aurora", "stateCode": "ISA" },
  { "name": "Benito Soliven", "stateCode": "ISA" },
  { "name": "Burgos", "stateCode": "ISA" },
  { "name": "Cabagan", "stateCode": "ISA" },
  { "name": "Cabatuan", "stateCode": "ISA" },
  { "name": "Cauayan", "stateCode": "ISA", "city": true },
  { "name": "Cordon", "stateCode": "ISA" },
  { "name": "Delfin Albano", "stateCode": "ISA" },
  { "name": "Dinapigue", "stateCode": "ISA" },
  { "name": "Divilacan", "stateCode": "ISA" },
  { "name": "Echague", "stateCode": "ISA" },
  { "name": "Gamu", "stateCode": "ISA" },
  { "name": "Ilagan", "stateCode": "ISA", "city": true },
  { "name": "Jones", "stateCode": "ISA" },
  { "name": "Luna", "stateCode": "ISA" },
  { "name": "Maconacon", "stateCode": "ISA" },
  { "name": "Mallig", "stateCode": "ISA" },
  { "name": "Naguilian", "stateCode": "ISA" },
  { "name": "Palanan", "stateCode": "ISA" },
  { "name": "Quezon", "stateCode": "ISA" },
  { "name": "Quirino", "stateCode": "ISA" },
  { "name": "Ramon", "stateCode": "ISA" },
  { "name": "Reina Mercedes", "stateCode": "ISA" },
  { "name": "Roxas", "stateCode": "ISA" },
  { "name": "San Agustin", "stateCode": "ISA" },
  { "name": "San Guillermo", "stateCode": "ISA" },
  { "name": "San Isidro", "stateCode": "ISA" },
  { "name": "San Manuel", "stateCode": "ISA" },
  { "name": "San Mariano", "stateCode": "ISA" },
  { "name": "San Mateo", "stateCode": "ISA" },
  { "name": "San Pablo", "stateCode": "ISA" },
  { "name": "Santa Maria", "stateCode": "ISA" },
  { "name": "Santiago", "stateCode": "ISA", "city": true },
  { "name": "Santo Tomas", "stateCode": "ISA" },
  { "name": "Tumauini", "stateCode": "ISA" },

  { "name": "Alfonso Castaneda", "stateCode": "NUV" },
  { "name": "Ambaguio", "stateCode": "NUV" },
  { "name": "Aritao", "stateCode": "NUV" },
  { "name": "Bagabag", "stateCode": "NUV" },
  { "name": "Bambang", "stateCode": "NUV" },
  { "name": "Bayombong", "stateCode": "NUV" },
  { "name": "Diadi", "stateCode": "NUV" },
  { "name": "Dupax del Norte", "stateCode": "NUV" },
  { "name": "Dupax del Sur", "stateCode": "NUV" },
  { "name": "Kasibu", "stateCode": "NUV" },
  { "name": "Kayapa", "stateCode": "NUV" },
  { "name": "Quezon", "stateCode": "NUV" },
  { "name": "Santa Fe", "stateCode": "NUV" },
  { "name": "Solano", "stateCode": "NUV" },
  { "name": "Villaverde", "stateCode": "NUV" },

  { "name": "Aglipay", "stateCode": "QUI" },
  { "name": "Cabarroguis", "stateCode": "QUI" },
  { "name": "Diffun", "stateCode": "QUI" },
  { "name": "Maddela", "stateCode": "QUI" },
  { "name": "Nagtipunan", "stateCode": "QUI" },
  { "name": "Saguday", "stateCode": "QUI" },

  { "name": "Baler", "stateCode": "AUR" },
  { "name": "Casiguran", "stateCode": "AUR" },
  { "name": "Dilasag", "stateCode": "AUR" },
  { "name": "Dinalungan", "stateCode": "AUR" },
  { "name": "Dingalan", "stateCode": "AUR" },
  { "name": "Dipaculao", "stateCode": "AUR" },
  { "name": "Maria Aurora", "stateCode": "AUR" },
  { "name": "San Luis", "stateCode": "AUR" },

  { "name": "Abucay", "stateCode": "BAN" },
  { "name": "Bagac", "stateCode": "BAN" },
  { "name": "Balanga", "stateCode": "BAN", "city": true },
  { "name": "Dinalupihan", "stateCode": "BAN" },
  { "name": "Hermosa", "stateCode": "BAN" },
  { "name": "Limay", "stateCode": "BAN" },
  { "name": "Mariveles", "stateCode": "BAN" },
  { "name": "Morong", "stateCode": "BAN" },
  { "name": "Orani", "stateCode": "BAN" },
  { "name": "Orion", "stateCode": "BAN" },
  { "name": "Pilar", "stateCode": "BAN" },
  { "name": "Samal", "stateCode": "BAN" },

  { "name": "Angat", "stateCode": "BUL" },
  { "name": "Balagtas", "stateCode": "BUL" },
  { "name": "Baliuag", "stateCode": "BUL" },
  { "name": "Bocaue", "stateCode": "BUL" },
  { "name": "Bulakan", "stateCode": "BUL" },
  { "name": "Bustos", "stateCode": "BUL" },
  { "name": "Calumpit", "stateCode": "BUL" },
  { "name": "Doña Remedios Trinidad", "stateCode": "BUL" },
  { "name": "Guiguinto", "stateCode": "BUL" },
  { "name": "Hagonoy", "stateCode": "BUL" },
  { "name": "Malolos", "stateCode": "BUL", "city": true },
  { "name": "Marilao", "stateCode": "BUL" },
  { "name": "Meycauayan", "stateCode": "BUL", "city": true },
  { "name": "Norzagaray", "stateCode": "BUL" },
  { "name": "Obando", "stateCode": "BUL" },
  { "name": "Pandi", "stateCode": "BUL" },
  { "name": "Paombong", "stateCode": "BUL" },
  { "name": "Plaridel", "stateCode": "BUL" },
  { "name": "Pulilan", "stateCode": "BUL" },
  { "name": "San Ildefonso", "stateCode": "BUL" },
  { "name": "San Jose del Monte", "stateCode": "BUL", "city": true },
  { "name": "San Miguel", "stateCode": "BUL" },
  { "name": "San Rafael", "stateCode": "BUL" },
  { "name": "Santa Maria", "stateCode": "BUL" },

  { "name": "Aliaga", "stateCode": "NUE" },
  { "name": "Bongabon", "stateCode": "NUE" },
  { "name": "Cabanatuan", "stateCode": "NUE", "city": true },
  { "name": "Cabiao", "stateCode": "NUE" },
  { "name": "Carranglan", "stateCode": "NUE" },
  { "name": "Cuyapo", "stateCode": "NUE" },
  { "name": "Gabaldon", "stateCode": "NUE" },
  { "name": "Gapan", "stateCode": "NUE", "city": true },
  { "name": "General Mamerto Natividad", "stateCode": "NUE" },
  { "name": "General Tinio", "stateCode": "NUE" },
  { "name": "Guimba", "stateCode": "NUE" },
  { "name": "Jaen", "stateCode": "NUE" },
  { "name": "Laur", "stateCode": "NUE" },
  { "name": "Licab", "stateCode": "NUE" },
  { "name": "Llanera", "stateCode": "NUE" },
  { "name": "Lupao", "stateCode": "NUE" },
  { "name": "Muñoz", "stateCode": "NUE", "city": true },
  { "name": "Nampicuan", "stateCode": "NUE" },
  { "name": "Palayan", "stateCode": "NUE", "city": true },
  { "name": "Pantabangan", "stateCode": "NUE" },
  { "name": "Peñaranda", "stateCode": "NUE" },
  { "name": "Quezon", "stateCode": "NUE" },
  { "name": "Rizal", "stateCode": "NUE" },
  { "name": "San Antonio", "stateCode": "NUE" },
  { "name": "San Isidro", "stateCode": "NUE" },
  { "name": "San Jose", "stateCode": "NUE", "city": true },
  { "name": "San Leonardo", "stateCode": "NUE" },
  { "name": "Santa Rosa", "stateCode": "NUE" },
  { "name": "Santo Domingo", "stateCode": "NUE" },
  { "name": "Talavera", "stateCode": "NUE" },
  { "name": "Talugtug", "stateCode": "NUE" },
  { "name": "Zaragoza", "stateCode": "NUE" },

  { "name": "Angeles", "stateCode": "PAM", "city": true },
  { "name": "Apalit", "stateCode": "PAM" },
  { "name": "Arayat", "stateCode": "PAM" },
  { "name": "Bacolor", "stateCode": "PAM" },
  { "name": "Candaba", "stateCode": "PAM" },
  { "name": "Floridablanca", "stateCode": "PAM" },
  { "name": "Guagua", "stateCode": "PAM" },
  { "name": "Lubao", "stateCode": "PAM" },
  { "name": "Mabalacat", "stateCode": "PAM", "city": true },
  { "name": "Macabebe", "stateCode": "PAM" },
  { "name": "Magalang", "stateCode": "PAM" },
  { "name": "Masantol", "stateCode": "PAM" },
  { "name": "Mexico", "stateCode": "PAM" },
  { "name": "Minalin", "stateCode": "PAM" },
  { "name": "Porac", "stateCode": "PAM" },
  { "name": "San Fernando", "stateCode": "PAM", "city": true },
  { "name": "San Luis", "stateCode": "PAM" },
  { "name": "San Simon", "stateCode": "PAM" },
  { "name": "Santa Ana", "stateCode": "PAM" },
  { "name": "Santa Rita", "stateCode": "PAM" },
  { "name": "Santo Tomas", "stateCode": "PAM" },
  { "name": "Sasmuan", "stateCode": "PAM" },

  { "name": "Anao", "stateCode": "TAR" },
  { "name": "Bamban", "stateCode": "TAR" },
  { "name": "Camiling", "stateCode": "TAR" },
  { "name": "Capas", "stateCode": "TAR" },
  { "name": "Concepcion", "stateCode": "TAR" },
  { "name": "Gerona", "stateCode": "TAR" },
  { "name": "La Paz", "stateCode": "TAR" },
  { "name": "Mayantoc", "stateCode": "TAR" },
  { "name": "Moncada", "stateCode": "TAR" },
  { "name": "Paniqui", "stateCode": "TAR" },
  { "name": "Pura", "stateCode": "TAR" },
  { "name": "Ramos", "stateCode": "TAR" },
  { "name": "San Clemente", "stateCode": "TAR" },
  { "name": "San Jose", "stateCode": "TAR" },
  { "name": "San Manuel", "stateCode": "TAR" },
  { "name": "Santa Ignacia", "stateCode": "TAR" },
  { "name": "Tarlac", "stateCode": "TAR", "city": true },
  { "name": "Victoria", "stateCode": "TAR" },

  { "name": "Botolan", "stateCode": "ZMB" },
  { "name": "Cabangan", "stateCode": "ZMB" },
  { "name": "Candelaria", "stateCode": "ZMB" },
  { "name": "Castillejos", "stateCode": "ZMB" },
  { "name": "Iba", "stateCode": "ZMB" },
  { "name": "Masinloc", "stateCode": "ZMB" },
  { "name": "Olongapo", "stateCode": "ZMB", "city": true },
  { "name": "Palauig", "stateCode": "ZMB" },
  { "name": "San Antonio", "stateCode": "ZMB" },
  { "name": "San Felipe", "stateCode": "ZMB" },
  { "name": "San Marcelino", "stateCode": "ZMB" },
  { "name": "San Narciso", "stateCode": "ZMB" },
  { "name": "Santa Cruz", "stateCode": "ZMB" },
  { "name": "Subic", "stateCode": "ZMB" },

  { "name": "Agoncillo", "stateCode": "BTG" },
  { "name": "Alitagtag", "stateCode": "BTG" },
  { "name": "Balayan", "stateCode": "BTG" },
  { "name": "Balete", "stateCode": "BTG" },
  { "name": "Batangas", "stateCode": "BTG", "city": true },
  { "name": "Bauan", "stateCode": "BTG" },
  { "name": "Calaca", "stateCode": "BTG" },
  { "name": "Calatagan", "stateCode": "BTG" },
  { "name": "Cuenca", "stateCode": "BTG" },
  { "name": "Ibaan", "stateCode": "BTG" },
  { "name": "Laurel", "stateCode": "BTG" },
  { "name": "Lemery", "stateCode": "BTG" },
  { "name": "Lian", "stateCode": "BTG" },
  { "name": "Lipa", "stateCode": "BTG", "city": true },
  { "name": "Lobo", "stateCode": "BTG" },
  { "name": "Mabini", "stateCode": "BTG" },
  { "name": "Malvar", "stateCode": "BTG" },
  { "name": "Mataasnakahoy", "stateCode": "BTG" },
  { "name": "Nasugbu", "stateCode": "BTG" },
  { "name": "Padre Garcia", "stateCode": "BTG" },
  { "name": "Rosario", "stateCode": "BTG" },
  { "name": "San Jose", "stateCode": "BTG" },
  { "name": "San Juan", "stateCode": "BTG" },
  { "name": "San Luis", "stateCode": "BTG" },
  { "name": "San Nicolas", "stateCode": "BTG" },
  { "name": "San Pascual", "stateCode": "BTG" },
  { "name": "Santa Teresita", "stateCode": "BTG" },
  { "name": "Santo Tomas", "stateCode": "BTG" },
  { "name": "Taal", "stateCode": "BTG" },
  { "name": "Talisay", "stateCode": "BTG" },
  { "name": "Tanauan", "stateCode": "BTG", "city": true },
  { "name": "Taysan", "stateCode": "BTG" },
  { "name": "Tingloy", "stateCode": "BTG" },
  { "name": "Tuy", "stateCode": "BTG" },

  { "name": "Alfonso", "stateCode": "CAV" },
  { "name": "Amadeo", "stateCode": "CAV" },
  { "name": "Bacoor", "stateCode": "CAV", "city": true },
  { "name": "Carmona", "stateCode": "CAV" },
  { "name": "Cavite", "stateCode": "CAV", "city": true },
  { "name": "Dasmariñas", "stateCode": "CAV", "city": true },
  { "name": "General Mariano Alvarez", "stateCode": "CAV" },
  { "name": "General Emilio Aguinaldo", "stateCode": "CAV" },
  { "name": "General Trias", "stateCode": "CAV" },
  { "name": "Imus", "stateCode": "CAV", "city": true },
  { "name": "Indang", "stateCode": "CAV" },
  { "name": "Kawit", "stateCode": "CAV" },
  { "name": "Magallanes", "stateCode": "CAV" },
  { "name": "Maragondon", "stateCode": "CAV" },
  { "name": "Mendez", "stateCode": "CAV" },
  { "name": "Naic", "stateCode": "CAV" },
  { "name": "Noveleta", "stateCode": "CAV" },
  { "name": "Rosario", "stateCode": "CAV" },
  { "name": "Silang", "stateCode": "CAV" },
  { "name": "Tagaytay", "stateCode": "CAV", "city": true },
  { "name": "Tanza", "stateCode": "CAV" },
  { "name": "Ternate", "stateCode": "CAV" },
  { "name": "Trece Martires", "stateCode": "CAV", "city": true },

  { "name": "Alaminos", "stateCode": "LAG" },
  { "name": "Bay", "stateCode": "LAG" },
  { "name": "Biñan", "stateCode": "LAG", "city": true },
  { "name": "Cabuyao", "stateCode": "LAG", "city": true },
  { "name": "Calamba", "stateCode": "LAG", "city": true },
  { "name": "Calauan", "stateCode": "LAG" },
  { "name": "Cavinti", "stateCode": "LAG" },
  { "name": "Famy", "stateCode": "LAG" },
  { "name": "Kalayaan", "stateCode": "LAG" },
  { "name": "Liliw", "stateCode": "LAG" },
  { "name": "Los Baños", "stateCode": "LAG" },
  { "name": "Luisiana", "stateCode": "LAG" },
  { "name": "Lumban", "stateCode": "LAG" },
  { "name": "Mabitac", "stateCode": "LAG" },
  { "name": "Magdalena", "stateCode": "LAG" },
  { "name": "Majayjay", "stateCode": "LAG" },
  { "name": "Nagcarlan", "stateCode": "LAG" },
  { "name": "Paete", "stateCode": "LAG" },
  { "name": "Pagsanjan", "stateCode": "LAG" },
  { "name": "Pakil", "stateCode": "LAG" },
  { "name": "Pangil", "stateCode": "LAG" },
  { "name": "Pila", "stateCode": "LAG" },
  { "name": "Rizal", "stateCode": "LAG" },
  { "name": "San Pablo", "stateCode": "LAG", "city": true },
  { "name": "San Pedro", "stateCode": "LAG", "city": true },
  { "name": "Santa Cruz", "stateCode": "LAG" },
  { "name": "Santa Maria", "stateCode": "LAG" },
  { "name": "Santa Rosa", "stateCode": "LAG", "city": true },
  { "name": "Siniloan", "stateCode": "LAG" },
  { "name": "Victoria", "stateCode": "LAG" },

  { "name": "Agdangan", "stateCode": "QUE" },
  { "name": "Alabat", "stateCode": "QUE" },
  { "name": "Atimonan", "stateCode": "QUE" },
  { "name": "Buenavista", "stateCode": "QUE" },
  { "name": "Burdeos", "stateCode": "QUE" },
  { "name": "Calauag", "stateCode": "QUE" },
  { "name": "Candelaria", "stateCode": "QUE" },
  { "name": "Catanauan", "stateCode": "QUE" },
  { "name": "Dolores", "stateCode": "QUE" },
  { "name": "General Luna", "stateCode": "QUE" },
  { "name": "General Nakar", "stateCode": "QUE" },
  { "name": "Guinayangan", "stateCode": "QUE" },
  { "name": "Gumaca", "stateCode": "QUE" },
  { "name": "Infanta", "stateCode": "QUE" },
  { "name": "Jomalig", "stateCode": "QUE" },
  { "name": "Lopez", "stateCode": "QUE" },
  { "name": "Lucban", "stateCode": "QUE" },
  { "name": "Lucena", "stateCode": "QUE", "city": true },
  { "name": "Macalelon", "stateCode": "QUE" },
  { "name": "Mauban", "stateCode": "QUE" },
  { "name": "Mulanay", "stateCode": "QUE" },
  { "name": "Padre Burgos", "stateCode": "QUE" },
  { "name": "Pagbilao", "stateCode": "QUE" },
  { "name": "Panukulan", "stateCode": "QUE" },
  { "name": "Patnanungan", "stateCode": "QUE" },
  { "name": "Perez", "stateCode": "QUE" },
  { "name": "Pitogo", "stateCode": "QUE" },
  { "name": "Plaridel", "stateCode": "QUE" },
  { "name": "Polillo", "stateCode": "QUE" },
  { "name": "Quezon", "stateCode": "QUE" },
  { "name": "Real", "stateCode": "QUE" },
  { "name": "Sampaloc", "stateCode": "QUE" },
  { "name": "San Andres", "stateCode": "QUE" },
  { "name": "San Antonio", "stateCode": "QUE" },
  { "name": "San Francisco", "stateCode": "QUE" },
  { "name": "San Narciso", "stateCode": "QUE" },
  { "name": "Sariaya", "stateCode": "QUE" },
  { "name": "Tagkawayan", "stateCode": "QUE" },
  { "name": "Tayabas", "stateCode": "QUE", "city": true },
  { "name": "Tiaong", "stateCode": "QUE" },
  { "name": "Unisan", "stateCode": "QUE" },

  { "name": "Angono", "stateCode": "RIZ" },
  { "name": "Antipolo", "stateCode": "RIZ", "city": true },
  { "name": "Baras", "stateCode": "RIZ" },
  { "name": "Binangonan", "stateCode": "RIZ" },
  { "name": "Cainta", "stateCode": "RIZ" },
  { "name": "Cardona", "stateCode": "RIZ" },
  { "name": "Jalajala", "stateCode": "RIZ" },
  { "name": "Morong", "stateCode": "RIZ" },
  { "name": "Pililla", "stateCode": "RIZ" },
  { "name": "Rodriguez", "stateCode": "RIZ" },
  { "name": "San Mateo", "stateCode": "RIZ" },
  { "name": "Tanay", "stateCode": "RIZ" },
  { "name": "Taytay", "stateCode": "RIZ" },
  { "name": "Teresa", "stateCode": "RIZ" },

  { "name": "Boac", "stateCode": "MAD" },
  { "name": "Buenavista", "stateCode": "MAD" },
  { "name": "Gasan", "stateCode": "MAD" },
  { "name": "Mogpog", "stateCode": "MAD" },
  { "name": "Santa Cruz", "stateCode": "MAD" },
  { "name": "Torrijos", "stateCode": "MAD" },

  { "name": "Abra de Ilog", "stateCode": "MDC" },
  { "name": "Calintaan", "stateCode": "MDC" },
  { "name": "Looc", "stateCode": "MDC" },
  { "name": "Lubang", "stateCode": "MDC" },
  { "name": "Magsaysay", "stateCode": "MDC" },
  { "name": "Mamburao", "stateCode": "MDC" },
  { "name": "Paluan", "stateCode": "MDC" },
  { "name": "Rizal", "stateCode": "MDC" },
  { "name": "Sablayan", "stateCode": "MDC" },
  { "name": "San Jose", "stateCode": "MDC" },
  { "name": "Santa Cruz", "stateCode": "MDC" },

  { "name": "Baco", "stateCode": "MDR" },
  { "name": "Bansud", "stateCode": "MDR" },
  { "name": "Bongabong", "stateCode": "MDR" },
  { "name": "Bulalacao", "stateCode": "MDR" },
  { "name": "Calapan", "stateCode": "MDR", "city": true },
  { "name": "Gloria", "stateCode": "MDR" },
  { "name": "Mansalay", "stateCode": "MDR" },
  { "name": "Naujan", "stateCode": "MDR" },
  { "name": "Pinamalayan", "stateCode": "MDR" },
  { "name": "Pola", "stateCode": "MDR" },
  { "name": "Puerto Galera", "stateCode": "MDR" },
  { "name": "Roxas", "stateCode": "MDR" },
  { "name": "San Teodoro", "stateCode": "MDR" },
  { "name": "Socorro", "stateCode": "MDR" },
  { "name": "Victoria", "stateCode": "MDR" },

  { "name": "Aborlan", "stateCode": "PLW" },
  { "name": "Agutaya", "stateCode": "PLW" },
  { "name": "Araceli", "stateCode": "PLW" },
  { "name": "Balabac", "stateCode": "PLW" },
  { "name": "Bataraza", "stateCode": "PLW" },
  { "name": "Brooke's Point", "stateCode": "PLW" },
  { "name": "Busuanga", "stateCode": "PLW" },
  { "name": "Cagayancillo", "stateCode": "PLW" },
  { "name": "Coron", "stateCode": "PLW" },
  { "name": "Culion", "stateCode": "PLW" },
  { "name": "Cuyo", "stateCode": "PLW" },
  { "name": "Dumaran", "stateCode": "PLW" },
  { "name": "El Nido", "stateCode": "PLW" },
  { "name": "Kalayaan", "stateCode": "PLW" },
  { "name": "Linapacan", "stateCode": "PLW" },
  { "name": "Magsaysay", "stateCode": "PLW" },
  { "name": "Narra", "stateCode": "PLW" },
  { "name": "Puerto Princesa", "stateCode": "PLW", "city": true },
  { "name": "Quezon", "stateCode": "PLW" },
  { "name": "Rizal", "stateCode": "PLW" },
  { "name": "Roxas", "stateCode": "PLW" },
  { "name": "San Vicente", "stateCode": "PLW" },
  { "name": "Sofronio Española", "stateCode": "PLW" },
  { "name": "Taytay", "stateCode": "PLW" },

  { "name": "Alcantara", "stateCode": "ROM" },
  { "name": "Banton", "stateCode": "ROM" },
  { "name": "Cajidiocan", "stateCode": "ROM" },
  { "name": "Calatrava", "stateCode": "ROM" },
  { "name": "Concepcion", "stateCode": "ROM" },
  { "name": "Corcuera", "stateCode": "ROM" },
  { "name": "Ferrol", "stateCode": "ROM" },
  { "name": "Looc", "stateCode": "ROM" },
  { "name": "Magdiwang", "stateCode": "ROM" },
  { "name": "Odiongan", "stateCode": "ROM" },
  { "name": "Romblon", "stateCode": "ROM" },
  { "name": "San Agustin", "stateCode": "ROM" },
  { "name": "San Andres", "stateCode": "ROM" },
  { "name": "San Fernando", "stateCode": "ROM" },
  { "name": "San Jose", "stateCode": "ROM" },
  { "name": "Santa Fe", "stateCode": "ROM" },
  { "name": "Santa Maria", "stateCode": "ROM" },

  { "name": "Bacacay", "stateCode": "ALB" },
  { "name": "Camalig", "stateCode": "ALB" },
  { "name": "Daraga", "stateCode": "ALB" },
  { "name": "Guinobatan", "stateCode": "ALB" },
  { "name": "Jovellar", "stateCode": "ALB" },
  { "name": "Legazpi", "stateCode": "ALB", "city": true },
  { "name": "Libon", "stateCode": "ALB" },
  { "name": "Ligao", "stateCode": "ALB", "city": true },
  { "name": "Malilipot", "stateCode": "ALB" },
  { "name": "Malinao", "stateCode": "ALB" },
  { "name": "Manito", "stateCode": "ALB" },
  { "name": "Oas", "stateCode": "ALB" },
  { "name": "Pio Duran", "stateCode": "ALB" },
  { "name": "Polangui", "stateCode": "ALB" },
  { "name": "Rapu-Rapu", "stateCode": "ALB" },
  { "name": "Santo Domingo", "stateCode": "ALB" },
  { "name": "Tabaco", "stateCode": "ALB", "city": true },
  { "name": "Tiwi", "stateCode": "ALB" },

  { "name": "Basud", "stateCode": "CAN" },
  { "name": "Capalonga", "stateCode": "CAN" },
  { "name": "Daet", "stateCode": "CAN" },
  { "name": "Jose Panganiban", "stateCode": "CAN" },
  { "name": "Labo", "stateCode": "CAN" },
  { "name": "Mercedes", "stateCode": "CAN" },
  { "name": "Paracale", "stateCode": "CAN" },
  { "name": "San Lorenzo Ruiz", "stateCode": "CAN" },
  { "name": "San Vicente", "stateCode": "CAN" },
  { "name": "Santa Elena", "stateCode": "CAN" },
  { "name": "Talisay", "stateCode": "CAN" },
  { "name": "Vinzons", "stateCode": "CAN" },

  { "name": "Baao", "stateCode": "CAS" },
  { "name": "Balatan", "stateCode": "CAS" },
  { "name": "Bato", "stateCode": "CAS" },
  { "name": "Bombon", "stateCode": "CAS" },
  { "name": "Buhi", "stateCode": "CAS" },
  { "name": "Bula", "stateCode": "CAS" },
  { "name": "Cabusao", "stateCode": "CAS" },
  { "name": "Calabanga", "stateCode": "CAS" },
  { "name": "Camaligan", "stateCode": "CAS" },
  { "name": "Canaman", "stateCode": "CAS" },
  { "name": "Caramoan", "stateCode": "CAS" },
  { "name": "Del Gallego", "stateCode": "CAS" },
  { "name": "Gainza", "stateCode": "CAS" },
  { "name": "Garchitorena", "stateCode": "CAS" },
  { "name": "Goa", "stateCode": "CAS" },
  { "name": "Iriga", "stateCode": "CAS", "city": true },
  { "name": "Lagonoy", "stateCode": "CAS" },
  { "name": "Libmanan", "stateCode": "CAS" },
  { "name": "Lupi", "stateCode": "CAS" },
  { "name": "Magarao", "stateCode": "CAS" },
  { "name": "Milaor", "stateCode": "CAS" },
  { "name": "Minalabac", "stateCode": "CAS" },
  { "name": "Nabua", "stateCode": "CAS" },
  { "name": "Naga", "stateCode": "CAS", "city": true },
  { "name": "Ocampo", "stateCode": "CAS" },
  { "name": "Pamplona", "stateCode": "CAS" },
  { "name": "Pasacao", "stateCode": "CAS" },
  { "name": "Pili", "stateCode": "CAS" },
  { "name": "Presentacion", "stateCode": "CAS" },
  { "name": "Ragay", "stateCode": "CAS" },
  { "name": "Sagñay", "stateCode": "CAS" },
  { "name": "San Fernando", "stateCode": "CAS" },
  { "name": "San Jose", "stateCode": "CAS" },
  { "name": "Sipocot", "stateCode": "CAS" },
  { "name": "Siruma", "stateCode": "CAS" },
  { "name": "Tigaon", "stateCode": "CAS" },
  { "name": "Tinambac", "stateCode": "CAS" },

  { "name": "Bagamanoc", "stateCode": "CAT" },
  { "name": "Baras", "stateCode": "CAT" },
  { "name": "Bato", "stateCode": "CAT" },
  { "name": "Caramoran", "stateCode": "CAT" },
  { "name": "Gigmoto", "stateCode": "CAT" },
  { "name": "Pandan", "stateCode": "CAT" },
  { "name": "Panganiban", "stateCode": "CAT" },
  { "name": "San Andres", "stateCode": "CAT" },
  { "name": "San Miguel", "stateCode": "CAT" },
  { "name": "Viga", "stateCode": "CAT" },
  { "name": "Virac", "stateCode": "CAT" },

  { "name": "Aroroy", "stateCode": "MAS" },
  { "name": "Baleno", "stateCode": "MAS" },
  { "name": "Balud", "stateCode": "MAS" },
  { "name": "Batuan", "stateCode": "MAS" },
  { "name": "Cataingan", "stateCode": "MAS" },
  { "name": "Cawayan", "stateCode": "MAS" },
  { "name": "Claveria", "stateCode": "MAS" },
  { "name": "Dimasalang", "stateCode": "MAS" },
  { "name": "Esperanza", "stateCode": "MAS" },
  { "name": "Mandaon", "stateCode": "MAS" },
  { "name": "Masbate", "stateCode": "MAS", "city": true },
  { "name": "Milagros", "stateCode": "MAS" },
  { "name": "Mobo", "stateCode": "MAS" },
  { "name": "Monreal", "stateCode": "MAS" },
  { "name": "Palanas", "stateCode": "MAS" },
  { "name": "Pio V. Corpuz", "stateCode": "MAS" },
  { "name": "Placer", "stateCode": "MAS" },
  { "name": "San Fernando", "stateCode": "MAS" },
  { "name": "San Jacinto", "stateCode": "MAS" },
  { "name": "San Pascual", "stateCode": "MAS" },
  { "name": "Uson", "stateCode": "MAS" },

  { "name": "Barcelona", "stateCode": "SOR" },
  { "name": "Bulan", "stateCode": "SOR" },
  { "name": "Bulusan", "stateCode": "SOR" },
  { "name": "Casiguran", "stateCode": "SOR" },
  { "name": "Castilla", "stateCode": "SOR" },
  { "name": "Donsol", "stateCode": "SOR" },
  { "name": "Gubat", "stateCode": "SOR" },
  { "name": "Irosin", "stateCode": "SOR" },
  { "name": "Juban", "stateCode": "SOR" },
  { "name": "Magallanes", "stateCode": "SOR" },
  { "name": "Matnog", "stateCode": "SOR" },
  { "name": "Pilar", "stateCode": "SOR" },
  { "name": "Prieto Diaz", "stateCode": "SOR" },
  { "name": "Santa Magdalena", "stateCode": "SOR" },
  { "name": "Sorsogon", "stateCode": "SOR", "city": true },

  { "name": "Altavas", "stateCode": "AKL" },
  { "name": "Balete", "stateCode": "AKL" },
  { "name": "Banga", "stateCode": "AKL" },
  { "name": "Batan", "stateCode": "AKL" },
  { "name": "Buruanga", "stateCode": "AKL" },
  { "name": "Ibajay", "stateCode": "AKL" },
  { "name": "Kalibo", "stateCode": "AKL" },
  { "name": "Lezo", "stateCode": "AKL" },
  { "name": "Libacao", "stateCode": "AKL" },
  { "name": "Madalag", "stateCode": "AKL" },
  { "name": "Makato", "stateCode": "AKL" },
  { "name": "Malay", "stateCode": "AKL" },
  { "name": "Malinao", "stateCode": "AKL" },
  { "name": "Nabas", "stateCode": "AKL" },
  { "name": "New Washington", "stateCode": "AKL" },
  { "name": "Numancia", "stateCode": "AKL" },
  { "name": "Tangalan", "stateCode": "AKL" },

  { "name": "Anini-y", "stateCode": "ANT" },
  { "name": "Barbaza", "stateCode": "ANT" },
  { "name": "Belison", "stateCode": "ANT" },
  { "name": "Bugasong", "stateCode": "ANT" },
  { "name": "Caluya", "stateCode": "ANT" },
  { "name": "Culasi", "stateCode": "ANT" },
  { "name": "Hamtic", "stateCode": "ANT" },
  { "name": "Laua-an", "stateCode": "ANT" },
  { "name": "Libertad", "stateCode": "ANT" },
  { "name": "Pandan", "stateCode": "ANT" },
  { "name": "Patnongon", "stateCode": "ANT" },
  { "name": "San Jose", "stateCode": "ANT" },
  { "name": "San Remigio", "stateCode": "ANT" },
  { "name": "Sebaste", "stateCode": "ANT" },
  { "name": "Sibalom", "stateCode": "ANT" },
  { "name": "Tibiao", "stateCode": "ANT" },
  { "name": "Tobias Fornier", "stateCode": "ANT" },
  { "name": "Valderrama", "stateCode": "ANT" },

  { "name": "Cuartero", "stateCode": "CAP" },
  { "name": "Dao", "stateCode": "CAP" },
  { "name": "Dumalag", "stateCode": "CAP" },
  { "name": "Dumarao", "stateCode": "CAP" },
  { "name": "Ivisan", "stateCode": "CAP" },
  { "name": "Jamindan", "stateCode": "CAP" },
  { "name": "Maayon", "stateCode": "CAP" },
  { "name": "Mambusao", "stateCode": "CAP" },
  { "name": "Panay", "stateCode": "CAP" },
  { "name": "Panitan", "stateCode": "CAP" },
  { "name": "Pilar", "stateCode": "CAP" },
  { "name": "Pontevedra", "stateCode": "CAP" },
  { "name": "President Roxas", "stateCode": "CAP" },
  { "name": "Roxas", "stateCode": "CAP", "city": true },
  { "name": "Sapian", "stateCode": "CAP" },
  { "name": "Sigma", "stateCode": "CAP" },
  { "name": "Tapaz", "stateCode": "CAP" },

  { "name": "Buenavista", "stateCode": "GUI" },
  { "name": "Jordan", "stateCode": "GUI" },
  { "name": "Nueva Valencia", "stateCode": "GUI" },
  { "name": "San Lorenzo", "stateCode": "GUI" },
  { "name": "Sibunag", "stateCode": "GUI" },

  { "name": "Ajuy", "stateCode": "ILI" },
  { "name": "Alimodian", "stateCode": "ILI" },
  { "name": "Anilao", "stateCode": "ILI" },
  { "name": "Badiangan", "stateCode": "ILI" },
  { "name": "Balasan", "stateCode": "ILI" },
  { "name": "Banate", "stateCode": "ILI" },
  { "name": "Barotac Nuevo", "stateCode": "ILI" },
  { "name": "Barotac Viejo", "stateCode": "ILI" },
  { "name": "Batad", "stateCode": "ILI" },
  { "name": "Bingawan", "stateCode": "ILI" },
  { "name": "Cabatuan", "stateCode": "ILI" },
  { "name": "Calinog", "stateCode": "ILI" },
  { "name": "Carles", "stateCode": "ILI" },
  { "name": "Concepcion", "stateCode": "ILI" },
  { "name": "Dingle", "stateCode": "ILI" },
  { "name": "Dueñas", "stateCode": "ILI" },
  { "name": "Dumangas", "stateCode": "ILI" },
  { "name": "Estancia", "stateCode": "ILI" },
  { "name": "Guimbal", "stateCode": "ILI" },
  { "name": "Igbaras", "stateCode": "ILI" },
  { "name": "Iloilo", "stateCode": "ILI", "city": true },
  { "name": "Janiuay", "stateCode": "ILI" },
  { "name": "Lambunao", "stateCode": "ILI" },
  { "name": "Leganes", "stateCode": "ILI" },
  { "name": "Lemery", "stateCode": "ILI" },
  { "name": "Leon", "stateCode": "ILI" },
  { "name": "Maasin", "stateCode": "ILI" },
  { "name": "Miagao", "stateCode": "ILI" },
  { "name": "Mina", "stateCode": "ILI" },
  { "name": "New Lucena", "stateCode": "ILI" },
  { "name": "Oton", "stateCode": "ILI" },
  { "name": "Passi", "stateCode": "ILI", "city": true },
  { "name": "Pavia", "stateCode": "ILI" },
  { "name": "Pototan", "stateCode": "ILI" },
  { "name": "San Dionisio", "stateCode": "ILI" },
  { "name": "San Enrique", "stateCode": "ILI" },
  { "name": "San Joaquin", "stateCode": "ILI" },
  { "name": "San Miguel", "stateCode": "ILI" },
  { "name": "San Rafael", "stateCode": "ILI" },
  { "name": "Santa Barbara", "stateCode": "ILI" },
  { "name": "Sara", "stateCode": "ILI" },
  { "name": "Tigbauan", "stateCode": "ILI" },
  { "name": "Tubungan", "stateCode": "ILI" },
  { "name": "Zarraga", "stateCode": "ILI" },

  { "name": "Bacolod", "stateCode": "NEC", "city": true },
  { "name": "Bago", "stateCode": "NEC", "city": true },
  { "name": "Binalbagan", "stateCode": "NEC" },
  { "name": "Cadiz", "stateCode": "NEC", "city": true },
  { "name": "Calatrava", "stateCode": "NEC" },
  { "name": "Candoni", "stateCode": "NEC" },
  { "name": "Cauayan", "stateCode": "NEC" },
  { "name": "Enrique B. Magalona", "stateCode": "NEC" },
  { "name": "Escalante", "stateCode": "NEC", "city": true },
  { "name": "Himamaylan", "stateCode": "NEC", "city": true },
  { "name": "Hinigaran", "stateCode": "NEC" },
  { "name": "Hinoba-an", "stateCode": "NEC" },
  { "name": "Ilog", "stateCode": "NEC" },
  { "name": "Isabela", "stateCode": "NEC" },
  { "name": "Kabankalan", "stateCode": "NEC", "city": true },
  { "name": "La Carlota", "stateCode": "NEC", "city": true },
  { "name": "La Castellana", "stateCode": "NEC" },
  { "name": "Manapla", "stateCode": "NEC" },
  { "name": "Moises Padilla", "stateCode": "NEC" },
  { "name": "Murcia", "stateCode": "NEC" },
  { "name": "Pontevedra", "stateCode": "NEC" },
  { "name": "Pulupandan", "stateCode": "NEC" },
  { "name": "Sagay", "stateCode": "NEC", "city": true },
  { "name": "Salvador Benedicto", "stateCode": "NEC" },
  { "name": "San Carlos", "stateCode": "NEC", "city": true },
  { "name": "San Enrique", "stateCode": "NEC" },
  { "name": "Silay", "stateCode": "NEC", "city": true },
  { "name": "Sipalay", "stateCode": "NEC", "city": true },
  { "name": "Talisay", "stateCode": "NEC", "city": true },
  { "name": "Toboso", "stateCode": "NEC" },
  { "name": "Valladolid", "stateCode": "NEC" },
  { "name": "Victorias", "stateCode": "NEC", "city": true },

  { "name": "Alburquerque", "stateCode": "BOH" },
  { "name": "Alicia", "stateCode": "BOH" },
  { "name": "Anda", "stateCode": "BOH" },
  { "name": "Antequera", "stateCode": "BOH" },
  { "name": "Baclayon", "stateCode": "BOH" },
  { "name": "Balilihan", "stateCode": "BOH" },
  { "name": "Batuan", "stateCode": "BOH" },
  { "name": "Bien Unido", "stateCode": "BOH" },
  { "name": "Bilar", "stateCode": "BOH" },
  { "name": "Buenavista", "stateCode": "BOH" },
  { "name": "Calape", "stateCode": "BOH" },
  { "name": "Candijay", "stateCode": "BOH" },
  { "name": "Carmen", "stateCode": "BOH" },
  { "name": "Catigbian", "stateCode": "BOH" },
  { "name": "Clarin", "stateCode": "BOH" },
  { "name": "Corella", "stateCode": "BOH" },
  { "name": "Cortes", "stateCode": "BOH" },
  { "name": "Dagohoy", "stateCode": "BOH" },
  { "name": "Danao", "stateCode": "BOH" },
  { "name": "Dauis", "stateCode": "BOH" },
  { "name": "Dimiao", "stateCode": "BOH" },
  { "name": "Duero", "stateCode": "BOH" },
  { "name": "Garcia Hernandez", "stateCode": "BOH" },
  { "name": "Getafe", "stateCode": "BOH" },
  { "name": "Guindulman", "stateCode": "BOH" },
  { "name": "Inabanga", "stateCode": "BOH" },
  { "name": "Jagna", "stateCode": "BOH" },
  { "name": "Lila", "stateCode": "BOH" },
  { "name": "Loay", "stateCode": "BOH" },
  { "name": "Loboc", "stateCode": "BOH" },
  { "name": "Loon", "stateCode": "BOH" },
  { "name": "Mabini", "stateCode": "BOH" },
  { "name": "Maribojoc", "stateCode": "BOH" },
  { "name": "Panglao", "stateCode": "BOH" },
  { "name": "Pilar", "stateCode": "BOH" },
  { "name": "President Carlos P. Garcia", "stateCode": "BOH" },
  { "name": "Sagbayan", "stateCode": "BOH" },
  { "name": "San Isidro", "stateCode": "BOH" },
  { "name": "San Miguel", "stateCode": "BOH" },
  { "name": "Sevilla", "stateCode": "BOH" },
  { "name": "Sierra Bullones", "stateCode": "BOH" },
  { "name": "Sikatuna", "stateCode": "BOH" },
  { "name": "Tagbilaran", "stateCode": "BOH", "city": true },
  { "name": "Talibon", "stateCode": "BOH" },
  { "name": "Trinidad", "stateCode": "BOH" },
  { "name": "Tubigon", "stateCode": "BOH" },
  { "name": "Ubay", "stateCode": "BOH" },
  { "name": "Valencia", "stateCode": "BOH" },

  { "name": "Alcantara", "stateCode": "CEB" },
  { "name": "Alcoy", "stateCode": "CEB" },
  { "name": "Alegria", "stateCode": "CEB" },
  { "name": "Aloguinsan", "stateCode": "CEB" },
  { "name": "Argao", "stateCode": "CEB" },
  { "name": "Asturias", "stateCode": "CEB" },
  { "name": "Badian", "stateCode": "CEB" },
  { "name": "Balamban", "stateCode": "CEB" },
  { "name": "Bantayan", "stateCode": "CEB" },
  { "name": "Barili", "stateCode": "CEB" },
  { "name": "Bogo", "stateCode": "CEB", "city": true },
  { "name": "Boljoon", "stateCode": "CEB" },
  { "name": "Borbon", "stateCode": "CEB" },
  { "name": "Carcar", "stateCode": "CEB", "city": true },
  { "name": "Carmen", "stateCode": "CEB" },
  { "name": "Catmon", "stateCode": "CEB" },
  { "name": "Cebu", "stateCode": "CEB", "city": true },
  { "name": "Compostela", "stateCode": "CEB" },
  { "name": "Consolacion", "stateCode": "CEB" },
  { "name": "Cordoba", "stateCode": "CEB" },
  { "name": "Daanbantayan", "stateCode": "CEB" },
  { "name": "Dalaguete", "stateCode": "CEB" },
  { "name": "Danao", "stateCode": "CEB", "city": true },
  { "name": "Dumanjug", "stateCode": "CEB" },
  { "name": "Ginatilan", "stateCode": "CEB" },
  { "name": "Lapu-Lapu", "stateCode": "CEB", "city": true },
  { "name": "Liloan", "stateCode": "CEB" },
  { "name": "Madridejos", "stateCode": "CEB" },
  { "name": "Malabuyoc", "stateCode": "CEB" },
  { "name": "Mandaue", "stateCode": "CEB", "city": true },
  { "name": "Medellin", "stateCode": "CEB" },
  { "name": "Minglanilla", "stateCode": "CEB" },
  { "name": "Moalboal", "stateCode": "CEB" },
  { "name": "Naga", "stateCode": "CEB", "city": true },
  { "name": "Oslob", "stateCode": "CEB" },
  { "name": "Pilar", "stateCode": "CEB" },
  { "name": "Pinamungajan", "stateCode": "CEB" },
  { "name": "Poro", "stateCode": "CEB" },
  { "name": "Ronda", "stateCode": "CEB" },
  { "name": "Samboan", "stateCode": "CEB" },
  { "name": "San Fernando", "stateCode": "CEB" },
  { "name": "San Francisco", "stateCode": "CEB" },
  { "name": "San Remigio", "stateCode": "CEB" },
  { "name": "Santa Fe", "stateCode": "CEB" },
  { "name": "Santander", "stateCode": "CEB" },
  { "name": "Sibonga", "stateCode": "CEB" },
  { "name": "Sogod", "stateCode": "CEB" },
  { "name": "Tabogon", "stateCode": "CEB" },
  { "name": "Tabuelan", "stateCode": "CEB" },
  { "name": "Talisay", "stateCode": "CEB", "city": true },
  { "name": "Toledo", "stateCode": "CEB", "city": true },
  { "name": "Tuburan", "stateCode": "CEB" },
  { "name": "Tudela", "stateCode": "CEB" },

  { "name": "Amlan", "stateCode": "NER" },
  { "name": "Ayungon", "stateCode": "NER" },
  { "name": "Bacong", "stateCode": "NER" },
  { "name": "Bais", "stateCode": "NER", "city": true },
  { "name": "Basay", "stateCode": "NER" },
  { "name": "Bayawan", "stateCode": "NER", "city": true },
  { "name": "Bindoy", "stateCode": "NER" },
  { "name": "Canlaon", "stateCode": "NER", "city": true },
  { "name": "Dauin", "stateCode": "NER" },
  { "name": "Dumaguete", "stateCode": "NER", "city": true },
  { "name": "Guihulngan", "stateCode": "NER", "city": true },
  { "name": "Jimalalud", "stateCode": "NER" },
  { "name": "La Libertad", "stateCode": "NER" },
  { "name": "Mabinay", "stateCode": "NER" },
  { "name": "Manjuyod", "stateCode": "NER" },
  { "name": "Pamplona", "stateCode": "NER" },
  { "name": "San Jose", "stateCode": "NER" },
  { "name": "Santa Catalina", "stateCode": "NER" },
  { "name": "Siaton", "stateCode": "NER" },
  { "name": "Sibulan", "stateCode": "NER" },
  { "name": "Tanjay", "stateCode": "NER", "city": true },
  { "name": "Tayasan", "stateCode": "NER" },
  { "name": "Valencia", "stateCode": "NER" },
  { "name": "Vallehermoso", "stateCode": "NER" },
  { "name": "Zamboanguita", "stateCode": "NER" },

  { "name": "Enrique Villanueva", "stateCode": "SIG" },
  { "name": "Larena", "stateCode": "SIG" },
  { "name": "Lazi", "stateCode": "SIG" },
  { "name": "Maria", "stateCode": "SIG" },
  { "name": "San Juan", "stateCode": "SIG" },
  { "name": "Siquijor", "stateCode": "SIG" },

  { "name": "Almeria", "stateCode": "BIL" },
  { "name": "Biliran", "stateCode": "BIL" },
  { "name": "Cabucgayan", "stateCode": "BIL" },
  { "name": "Caibiran", "stateCode": "BIL" },
  { "name": "Culaba", "stateCode": "BIL" },
  { "name": "Kawayan", "stateCode": "BIL" },
  { "name": "Maripipi", "stateCode": "BIL" },
  { "name": "Naval", "stateCode": "BIL" },

  { "name": "Arteche", "stateCode": "EAS" },
  { "name": "Balangiga", "stateCode": "EAS" },
  { "name": "Balangkayan", "stateCode": "EAS" },
  { "name": "Borongan", "stateCode": "EAS", "city": true },
  { "name": "Can-avid", "stateCode": "EAS" },
  { "name": "Dolores", "stateCode": "EAS" },
  { "name": "General MacArthur", "stateCode": "EAS" },
  { "name": "Giporlos", "stateCode": "EAS" },
  { "name": "Guiuan", "stateCode": "EAS" },
  { "name": "Hernani", "stateCode": "EAS" },
  { "name": "Jipapad", "stateCode": "EAS" },
  { "name": "Lawaan", "stateCode": "EAS" },
  { "name": "Llorente", "stateCode": "EAS" },
  { "name": "Maslog", "stateCode": "EAS" },
  { "name": "Maydolong", "stateCode": "EAS" },
  { "name": "Mercedes", "stateCode": "EAS" },
  { "name": "Oras", "stateCode": "EAS" },
  { "name": "Quinapondan", "stateCode": "EAS" },
  { "name": "Salcedo", "stateCode": "EAS" },
  { "name": "San Julian", "stateCode": "EAS" },
  { "name": "San Policarpo", "stateCode": "EAS" },
  { "name": "Sulat", "stateCode": "EAS" },
  { "name": "Taft", "stateCode": "EAS" },

  { "name": "Abuyog", "stateCode": "LEY" },
  { "name": "Alangalang", "stateCode": "LEY" },
  { "name": "Albuera", "stateCode": "LEY" },
  { "name": "Babatngon", "stateCode": "LEY" },
  { "name": "Barugo", "stateCode": "LEY" },
  { "name": "Bato", "stateCode": "LEY" },
  { "name": "Baybay", "stateCode": "LEY", "city": true },
  { "name": "Burauen", "stateCode": "LEY" },
  { "name": "Calubian", "stateCode": "LEY" },
  { "name": "Capoocan", "stateCode": "LEY" },
  { "name": "Carigara", "stateCode": "LEY" },
  { "name": "Dagami", "stateCode": "LEY" },
  { "name": "Dulag", "stateCode": "LEY" },
  { "name": "Hilongos", "stateCode": "LEY" },
  { "name": "Hindang", "stateCode": "LEY" },
  { "name": "Inopacan", "stateCode": "LEY" },
  { "name": "Isabel", "stateCode": "LEY" },
  { "name": "Jaro", "stateCode": "LEY" },
  { "name": "Javier", "stateCode": "LEY" },
  { "name": "Julita", "stateCode": "LEY" },
  { "name": "Kananga", "stateCode": "LEY" },
  { "name": "La Paz", "stateCode": "LEY" },
  { "name": "Leyte", "stateCode": "LEY" },
  { "name": "MacArthur", "stateCode": "LEY" },
  { "name": "Mahaplag", "stateCode": "LEY" },
  { "name": "Matag-ob", "stateCode": "LEY" },
  { "name": "Matalom", "stateCode": "LEY" },
  { "name": "Mayorga", "stateCode": "LEY" },
  { "name": "Merida", "stateCode": "LEY" },
  { "name": "Ormoc", "stateCode": "LEY", "city": true },
  { "name": "Palo", "stateCode": "LEY" },
  { "name": "Palompon", "stateCode": "LEY" },
  { "name": "Pastrana", "stateCode": "LEY" },
  { "name": "San Isidro", "stateCode": "LEY" },
  { "name": "San Miguel", "stateCode": "LEY" },
  { "name": "Santa Fe", "stateCode": "LEY" },
  { "name": "Tabango", "stateCode": "LEY" },
  { "name": "Tabontabon", "stateCode": "LEY" },
  { "name": "Tacloban", "stateCode": "LEY", "city": true },
  { "name": "Tanauan", "stateCode": "LEY" },
  { "name": "Tolosa", "stateCode": "LEY" },
  { "name": "Tunga", "stateCode": "LEY" },
  { "name": "Villaba", "stateCode": "LEY" },

  { "name": "Allen", "stateCode": "NSA" },
  { "name": "Biri", "stateCode": "NSA" },
  { "name": "Bobon", "stateCode": "NSA" },
  { "name": "Capul", "stateCode": "NSA" },
  { "name": "Catarman", "stateCode": "NSA" },
  { "name": "Catubig", "stateCode": "NSA" },
  { "name": "Gamay", "stateCode": "NSA" },
  { "name": "Laoang", "stateCode": "NSA" },
  { "name": "Lapinig", "stateCode": "NSA" },
  { "name": "Las Navas", "stateCode": "NSA" },
  { "name": "Lavezares", "stateCode": "NSA" },
  { "name": "Lope de Vega", "stateCode": "NSA" },
  { "name": "Mapanas", "stateCode": "NSA" },
  { "name": "Mondragon", "stateCode": "NSA" },
  { "name": "Palapag", "stateCode": "NSA" },
  { "name": "Pambujan", "stateCode": "NSA" },
  { "name": "Rosario", "stateCode": "NSA" },
  { "name": "San Antonio", "stateCode": "NSA" },
  { "name": "San Isidro", "stateCode": "NSA" },
  { "name": "San Jose", "stateCode": "NSA" },
  { "name": "San Roque", "stateCode": "NSA" },
  { "name": "San Vicente", "stateCode": "NSA" },
  { "name": "Silvino Lobos", "stateCode": "NSA" },
  { "name": "Victoria", "stateCode": "NSA" },

  { "name": "Almagro", "stateCode": "WSA" },
  { "name": "Basey", "stateCode": "WSA" },
  { "name": "Calbayog", "stateCode": "WSA", "city": true },
  { "name": "Calbiga", "stateCode": "WSA" },
  { "name": "Catbalogan", "stateCode": "WSA", "city": true },
  { "name": "Daram", "stateCode": "WSA" },
  { "name": "Gandara", "stateCode": "WSA" },
  { "name": "Hinabangan", "stateCode": "WSA" },
  { "name": "Jiabong", "stateCode": "WSA" },
  { "name": "Marabut", "stateCode": "WSA" },
  { "name": "Matuguinao", "stateCode": "WSA" },
  { "name": "Motiong", "stateCode": "WSA" },
  { "name": "Pagsanghan", "stateCode": "WSA" },
  { "name": "Paranas", "stateCode": "WSA" },
  { "name": "Pinabacdao", "stateCode": "WSA" },
  { "name": "San Jorge", "stateCode": "WSA" },
  { "name": "San Jose de Buan", "stateCode": "WSA" },
  { "name": "San Sebastian", "stateCode": "WSA" },
  { "name": "Santa Margarita", "stateCode": "WSA" },
  { "name": "Santa Rita", "stateCode": "WSA" },
  { "name": "Santo Niño", "stateCode": "WSA" },
  { "name": "Tagapul-an", "stateCode": "WSA" },
  { "name": "Talalora", "stateCode": "WSA" },
  { "name": "Tarangnan", "stateCode": "WSA" },
  { "name": "Villareal", "stateCode": "WSA" },
  { "name": "Zumarraga", "stateCode": "WSA" },

  { "name": "Anahawan", "stateCode": "SLE" },
  { "name": "Bontoc", "stateCode": "SLE" },
  { "name": "Hinunangan", "stateCode": "SLE" },
  { "name": "Hinundayan", "stateCode": "SLE" },
  { "name": "Libagon", "stateCode": "SLE" },
  { "name": "Liloan", "stateCode": "SLE" },
  { "name": "Limasawa", "stateCode": "SLE" },
  { "name": "Maasin", "stateCode": "SLE", "city": true },
  { "name": "Macrohon", "stateCode": "SLE" },
  { "name": "Malitbog", "stateCode": "SLE" },
  { "name": "Padre Burgos", "stateCode": "SLE" },
  { "name": "Pintuyan", "stateCode": "SLE" },
  { "name": "Saint Bernard", "stateCode": "SLE" },
  { "name": "San Francisco", "stateCode": "SLE" },
  { "name": "San Juan", "stateCode": "SLE" },
  { "name": "San Ricardo", "stateCode": "SLE" },
  { "name": "Silago", "stateCode": "SLE" },
  { "name": "Sogod", "stateCode": "SLE" },
  { "name": "Tomas Oppus", "stateCode": "SLE" },

  { "name": "Baliguian", "stateCode": "ZAN" },
  { "name": "Dapitan", "stateCode": "ZAN", "city": true },
  { "name": "Dipolog", "stateCode": "ZAN", "city": true },
  { "name": "Godod", "stateCode": "ZAN" },
  { "name": "Gutalac", "stateCode": "ZAN" },
  { "name": "Jose Dalman", "stateCode": "ZAN" },
  { "name": "Kalawit", "stateCode": "ZAN" },
  { "name": "Katipunan", "stateCode": "ZAN" },
  { "name": "La Libertad", "stateCode": "ZAN" },
  { "name": "Labason", "stateCode": "ZAN" },
  { "name": "Leon B. Postigo", "stateCode": "ZAN" },
  { "name": "Liloy", "stateCode": "ZAN" },
  { "name": "Manukan", "stateCode": "ZAN" },
  { "name": "Mutia", "stateCode": "ZAN" },
  { "name": "Piñan", "stateCode": "ZAN" },
  { "name": "Polanco", "stateCode": "ZAN" },
  { "name": "President Manuel A. Roxas", "stateCode": "ZAN" },
  { "name": "Rizal", "stateCode": "ZAN" },
  { "name": "Salug", "stateCode": "ZAN" },
  { "name": "Sergio Osmeña Sr.", "stateCode": "ZAN" },
  { "name": "Siayan", "stateCode": "ZAN" },
  { "name": "Sibuco", "stateCode": "ZAN" },
  { "name": "Sibutad", "stateCode": "ZAN" },
  { "name": "Sindangan", "stateCode": "ZAN" },
  { "name": "Siocon", "stateCode": "ZAN" },
  { "name": "Sirawai", "stateCode": "ZAN" },
  { "name": "Tampilisan", "stateCode": "ZAN" },

  { "name": "Aurora", "stateCode": "ZAS" },
  { "name": "Bayog", "stateCode": "ZAS" },
  { "name": "Dimataling", "stateCode": "ZAS" },
  { "name": "Dinas", "stateCode": "ZAS" },
  { "name": "Dumalinao", "stateCode": "ZAS" },
  { "name": "Dumingag", "stateCode": "ZAS" },
  { "name": "Guipos", "stateCode": "ZAS" },
  { "name": "Josefina", "stateCode": "ZAS" },
  { "name": "Kumalarang", "stateCode": "ZAS" },
  { "name": "Labangan", "stateCode": "ZAS" },
  { "name": "Lakewood", "stateCode": "ZAS" },
  { "name": "Lapuyan", "stateCode": "ZAS" },
  { "name": "Mahayag", "stateCode": "ZAS" },
  { "name": "Margosatubig", "stateCode": "ZAS" },
  { "name": "Midsalip", "stateCode": "ZAS" },
  { "name": "Molave", "stateCode": "ZAS" },
  { "name": "Pagadian", "stateCode": "ZAS", "city": true },
  { "name": "Pitogo", "stateCode": "ZAS" },
  { "name": "Ramon Magsaysay", "stateCode": "ZAS" },
  { "name": "San Miguel", "stateCode": "ZAS" },
  { "name": "San Pablo", "stateCode": "ZAS" },
  { "name": "Sominot", "stateCode": "ZAS" },
  { "name": "Tabina", "stateCode": "ZAS" },
  { "name": "Tambulig", "stateCode": "ZAS" },
  { "name": "Tigbao", "stateCode": "ZAS" },
  { "name": "Tukuran", "stateCode": "ZAS" },
  { "name": "Vincenzo A. Sagun", "stateCode": "ZAS" },
  { "name": "Zamboanga", "stateCode": "ZAS", "city": true },

  { "name": "Alicia", "stateCode": "ZSI" },
  { "name": "Buug", "stateCode": "ZSI" },
  { "name": "Diplahan", "stateCode": "ZSI" },
  { "name": "Imelda", "stateCode": "ZSI" },
  { "name": "Ipil", "stateCode": "ZSI" },
  { "name": "Kabasalan", "stateCode": "ZSI" },
  { "name": "Mabuhay", "stateCode": "ZSI" },
  { "name": "Malangas", "stateCode": "ZSI" },
  { "name": "Naga", "stateCode": "ZSI" },
  { "name": "Olutanga", "stateCode": "ZSI" },
  { "name": "Payao", "stateCode": "ZSI" },
  { "name": "Roseller Lim", "stateCode": "ZSI" },
  { "name": "Siay", "stateCode": "ZSI" },
  { "name": "Talusan", "stateCode": "ZSI" },
  { "name": "Titay", "stateCode": "ZSI" },
  { "name": "Tungawan", "stateCode": "ZSI" },

  { "name": "Baungon", "stateCode": "BUK" },
  { "name": "Cabanglasan", "stateCode": "BUK" },
  { "name": "Damulog", "stateCode": "BUK" },
  { "name": "Dangcagan", "stateCode": "BUK" },
  { "name": "Don Carlos", "stateCode": "BUK" },
  { "name": "Impasugong", "stateCode": "BUK" },
  { "name": "Kadingilan", "stateCode": "BUK" },
  { "name": "Kalilangan", "stateCode": "BUK" },
  { "name": "Kibawe", "stateCode": "BUK" },
  { "name": "Kitaotao", "stateCode": "BUK" },
  { "name": "Lantapan", "stateCode": "BUK" },
  { "name": "Libona", "stateCode": "BUK" },
  { "name": "Malaybalay", "stateCode": "BUK", "city": true },
  { "name": "Malitbog", "stateCode": "BUK" },
  { "name": "Manolo Fortich", "stateCode": "BUK" },
  { "name": "Maramag", "stateCode": "BUK" },
  { "name": "Pangantucan", "stateCode": "BUK" },
  { "name": "Quezon", "stateCode": "BUK" },
  { "name": "San Fernando", "stateCode": "BUK" },
  { "name": "Sumilao", "stateCode": "BUK" },
  { "name": "Talakag", "stateCode": "BUK" },
  { "name": "Valencia", "stateCode": "BUK", "city": true },

  { "name": "Catarman", "stateCode": "CAM" },
  { "name": "Guinsiliban", "stateCode": "CAM" },
  { "name": "Mahinog", "stateCode": "CAM" },
  { "name": "Mambajao", "stateCode": "CAM" },
  { "name": "Sagay", "stateCode": "CAM" },

  { "name": "Bacolod", "stateCode": "LAN" },
  { "name": "Baloi", "stateCode": "LAN" },
  { "name": "Baroy", "stateCode": "LAN" },
  { "name": "Iligan", "stateCode": "LAN", "city": true },
  { "name": "Kapatagan", "stateCode": "LAN" },
  { "name": "Kauswagan", "stateCode": "LAN" },
  { "name": "Kolambugan", "stateCode": "LAN" },
  { "name": "Lala", "stateCode": "LAN" },
  { "name": "Linamon", "stateCode": "LAN" },
  { "name": "Magsaysay", "stateCode": "LAN" },
  { "name": "Maigo", "stateCode": "LAN" },
  { "name": "Matungao", "stateCode": "LAN" },
  { "name": "Munai", "stateCode": "LAN" },
  { "name": "Nunungan", "stateCode": "LAN" },
  { "name": "Pantao Ragat", "stateCode": "LAN" },
  { "name": "Pantar", "stateCode": "LAN" },
  { "name": "Poona Piagapo", "stateCode": "LAN" },
  { "name": "Salvador", "stateCode": "LAN" },
  { "name": "Sapad", "stateCode": "LAN" },
  { "name": "Sultan Naga Dimaporo", "stateCode": "LAN" },
  { "name": "Tagoloan", "stateCode": "LAN" },
  { "name": "Tangcal", "stateCode": "LAN" },
  { "name": "Tubod", "stateCode": "LAN" },

  { "name": "Aloran", "stateCode": "MSC" },
  { "name": "Baliangao", "stateCode": "MSC" },
  { "name": "Bonifacio", "stateCode": "MSC" },
  { "name": "Calamba", "stateCode": "MSC" },
  { "name": "Clarin", "stateCode": "MSC" },
  { "name": "Concepcion", "stateCode": "MSC" },
  { "name": "Don Victoriano Chiongbian", "stateCode": "MSC" },
  { "name": "Jimenez", "stateCode": "MSC" },
  { "name": "Lopez Jaena", "stateCode": "MSC" },
  { "name": "Oroquieta", "stateCode": "MSC", "city": true },
  { "name": "Ozamiz", "stateCode": "MSC", "city": true },
  { "name": "Panaon", "stateCode": "MSC" },
  { "name": "Plaridel", "stateCode": "MSC" },
  { "name": "Sapang Dalaga", "stateCode": "MSC" },
  { "name": "Sinacaban", "stateCode": "MSC" },
  { "name": "Tangub", "stateCode": "MSC", "city": true },
  { "name": "Tudela", "stateCode": "MSC" },

  { "name": "Alubijid", "stateCode": "MSR" },
  { "name": "Balingasag", "stateCode": "MSR" },
  { "name": "Balingoan", "stateCode": "MSR" },
  { "name": "Binuangan", "stateCode": "MSR" },
  { "name": "Cagayan de Oro", "stateCode": "MSR", "city": true },
  { "name": "Claveria", "stateCode": "MSR" },
  { "name": "El Salvador", "stateCode": "MSR", "city": true },
  { "name": "Gingoog", "stateCode": "MSR", "city": true },
  { "name": "Gitagum", "stateCode": "MSR" },
  { "name": "Initao", "stateCode": "MSR" },
  { "name": "Jasaan", "stateCode": "MSR" },
  { "name": "Kinoguitan", "stateCode": "MSR" },
  { "name": "Lagonglong", "stateCode": "MSR" },
  { "name": "Laguindingan", "stateCode": "MSR" },
  { "name": "Libertad", "stateCode": "MSR" },
  { "name": "Lugait", "stateCode": "MSR" },
  { "name": "Magsaysay", "stateCode": "MSR" },
  { "name": "Manticao", "stateCode": "MSR" },
  { "name": "Medina", "stateCode": "MSR" },
  { "name": "Naawan", "stateCode": "MSR" },
  { "name": "Opol", "stateCode": "MSR" },
  { "name": "Salay", "stateCode": "MSR" },
  { "name": "Sugbongcogon", "stateCode": "MSR" },
  { "name": "Tagoloan", "stateCode": "MSR" },
  { "name": "Talisayan", "stateCode": "MSR" },
  { "name": "Villanueva", "stateCode": "MSR" },

  { "name": "Compostela", "stateCode": "COM" },
  { "name": "Laak", "stateCode": "COM" },
  { "name": "Mabini", "stateCode": "COM" },
  { "name": "Maco", "stateCode": "COM" },
  { "name": "Maragusan", "stateCode": "COM" },
  { "name": "Mawab", "stateCode": "COM" },
  { "name": "Monkayo", "stateCode": "COM" },
  { "name": "Montevista", "stateCode": "COM" },
  { "name": "Nabunturan", "stateCode": "COM" },
  { "name": "New Bataan", "stateCode": "COM" },
  { "name": "Pantukan", "stateCode": "COM" },

  { "name": "Asuncion", "stateCode": "DAV" },
  { "name": "Braulio E. Dujali", "stateCode": "DAV" },
  { "name": "Carmen", "stateCode": "DAV" },
  { "name": "Kapalong", "stateCode": "DAV" },
  { "name": "New Corella", "stateCode": "DAV" },
  { "name": "Panabo", "stateCode": "DAV", "city": true },
  { "name": "Samal", "stateCode": "DAV", "city": true },
  { "name": "San Isidro", "stateCode": "DAV" },
  { "name": "Santo Tomas", "stateCode": "DAV" },
  { "name": "Tagum", "stateCode": "DAV", "city": true },
  { "name": "Talaingod", "stateCode": "DAV" },

  { "name": "Bansalan", "stateCode": "DAS" },
  { "name": "Davao", "stateCode": "DAS", "city": true },
  { "name": "Digos", "stateCode": "DAS", "city": true },
  { "name": "Hagonoy", "stateCode": "DAS" },
  { "name": "Kiblawan", "stateCode": "DAS" },
  { "name": "Magsaysay", "stateCode": "DAS" },
  { "name": "Malalag", "stateCode": "DAS" },
  { "name": "Matanao", "stateCode": "DAS" },
  { "name": "Padada", "stateCode": "DAS" },
  { "name": "Santa Cruz", "stateCode": "DAS" },
  { "name": "Sulop", "stateCode": "DAS" },

  { "name": "Don Marcelino", "stateCode": "DAC" },
  { "name": "Jose Abad Santos", "stateCode": "DAC" },
  { "name": "Malita", "stateCode": "DAC" },
  { "name": "Santa Maria", "stateCode": "DAC" },
  { "name": "Sarangani", "stateCode": "DAC" },

  { "name": "Baganga", "stateCode": "DAO" },
  { "name": "Banaybanay", "stateCode": "DAO" },
  { "name": "Boston", "stateCode": "DAO" },
  { "name": "Caraga", "stateCode": "DAO" },
  { "name": "Cateel", "stateCode": "DAO" },
  { "name": "Governor Generoso", "stateCode": "DAO" },
  { "name": "Lupon", "stateCode": "DAO" },
  { "name": "Manay", "stateCode": "DAO" },
  { "name": "Mati", "stateCode": "DAO", "city": true },
  { "name": "San Isidro", "stateCode": "DAO" },
  { "name": "Tarragona", "stateCode": "DAO" },

  { "name": "Alamada", "stateCode": "NCO" },
  { "name": "Aleosan", "stateCode": "NCO" },
  { "name": "Antipas", "stateCode": "NCO" },
  { "name": "Arakan", "stateCode": "NCO" },
  { "name": "Banisilan", "stateCode": "NCO" },
  { "name": "Carmen", "stateCode": "NCO" },
  { "name": "Kabacan", "stateCode": "NCO" },
  { "name": "Kidapawan", "stateCode": "NCO", "city": true },
  { "name": "Libungan", "stateCode": "NCO" },
  { "name": "M'lang", "stateCode": "NCO" },
  { "name": "Magpet", "stateCode": "NCO" },
  { "name": "Makilala", "stateCode": "NCO" },
  { "name": "Matalam", "stateCode": "NCO" },
  { "name": "Midsayap", "stateCode": "NCO" },
  { "name": "Pigcawayan", "stateCode": "NCO" },
  { "name": "Pikit", "stateCode": "NCO" },
  { "name": "President Roxas", "stateCode": "NCO" },
  { "name": "Tulunan", "stateCode": "NCO" },

  { "name": "Alabel", "stateCode": "SAR" },
  { "name": "Glan", "stateCode": "SAR" },
  { "name": "Kiamba", "stateCode": "SAR" },
  { "name": "Maasim", "stateCode": "SAR" },
  { "name": "Maitum", "stateCode": "SAR" },
  { "name": "Malapatan", "stateCode": "SAR" },
  { "name": "Malungon", "stateCode": "SAR" },

  { "name": "Banga", "stateCode": "SCO" },
  { "name": "General Santos", "stateCode": "SCO", "city": true },
  { "name": "Koronadal", "stateCode": "SCO", "city": true },
  { "name": "Lake Sebu", "stateCode": "SCO" },
  { "name": "Norala", "stateCode": "SCO" },
  { "name": "Polomolok", "stateCode": "SCO" },
  { "name": "Santo Niño", "stateCode": "SCO" },
  { "name": "Surallah", "stateCode": "SCO" },
  { "name": "T'boli", "stateCode": "SCO" },
  { "name": "Tampakan", "stateCode": "SCO" },
  { "name": "Tantangan", "stateCode": "SCO" },
  { "name": "Tupi", "stateCode": "SCO" },

  { "name": "Bagumbayan", "stateCode": "SUK" },
  { "name": "Columbio", "stateCode": "SUK" },
  { "name": "Esperanza", "stateCode": "SUK" },
  { "name": "Isulan", "stateCode": "SUK" },
  { "name": "Kalamansig", "stateCode": "SUK" },
  { "name": "Lambayong", "stateCode": "SUK" },
  { "name": "Lebak", "stateCode": "SUK" },
  { "name": "Lutayan", "stateCode": "SUK" },
  { "name": "Palimbang", "stateCode": "SUK" },
  { "name": "President Quirino", "stateCode": "SUK" },
  { "name": "Senator Ninoy Aquino", "stateCode": "SUK" },
  { "name": "Tacurong", "stateCode": "SUK", "city": true },

  { "name": "Buenavista", "stateCode": "AGN" },
  { "name": "Butuan", "stateCode": "AGN", "city": true },
  { "name": "Cabadbaran", "stateCode": "AGN", "city": true },
  { "name": "Carmen", "stateCode": "AGN" },
  { "name": "Jabonga", "stateCode": "AGN" },
  { "name": "Kitcharao", "stateCode": "AGN" },
  { "name": "Las Nieves", "stateCode": "AGN" },
  { "name": "Magallanes", "stateCode": "AGN" },
  { "name": "Nasipit", "stateCode": "AGN" },
  { "name": "Remedios T. Romualdez", "stateCode": "AGN" },
  { "name": "Santiago", "stateCode": "AGN" },
  { "name": "Tubay", "stateCode": "AGN" },

  { "name": "Bayugan", "stateCode": "AGS", "city": true },
  { "name": "Bunawan", "stateCode": "AGS" },
  { "name": "Esperanza", "stateCode": "AGS" },
  { "name": "La Paz", "stateCode": "AGS" },
  { "name": "Loreto", "stateCode": "AGS" },
  { "name": "Prosperidad", "stateCode": "AGS" },
  { "name": "Rosario", "stateCode": "AGS" },
  { "name": "San Francisco", "stateCode": "AGS" },
  { "name": "San Luis", "stateCode": "AGS" },
  { "name": "Santa Josefa", "stateCode": "AGS" },
  { "name": "Sibagat", "stateCode": "AGS" },
  { "name": "Talacogon", "stateCode": "AGS" },
  { "name": "Trento", "stateCode": "AGS" },
  { "name": "Veruela", "stateCode": "AGS" },

  { "name": "Basilisa", "stateCode": "DIN" },
  { "name": "Cagdianao", "stateCode": "DIN" },
  { "name": "Dinagat", "stateCode": "DIN" },
  { "name": "Libjo", "stateCode": "DIN" },
  { "name": "Loreto", "stateCode": "DIN" },
  { "name": "San Jose", "stateCode": "DIN" },
  { "name": "Tubajon", "stateCode": "DIN" },

  { "name": "Alegria", "stateCode": "SUN" },
  { "name": "Bacuag", "stateCode": "SUN" },
  { "name": "Burgos", "stateCode": "SUN" },
  { "name": "Claver", "stateCode": "SUN" },
  { "name": "Dapa", "stateCode": "SUN" },
  { "name": "Del Carmen", "stateCode": "SUN" },
  { "name": "General Luna", "stateCode": "SUN" },
  { "name": "Gigaquit", "stateCode": "SUN" },
  { "name": "Mainit", "stateCode": "SUN" },
  { "name": "Malimono", "stateCode": "SUN" },
  { "name": "Pilar", "stateCode": "SUN" },
  { "name": "Placer", "stateCode": "SUN" },
  { "name": "San Benito", "stateCode": "SUN" },
  { "name": "San Francisco", "stateCode": "SUN" },
  { "name": "San Isidro", "stateCode": "SUN" },
  { "name": "Santa Monica", "stateCode": "SUN" },
  { "name": "Sison", "stateCode": "SUN" },
  { "name": "Socorro", "stateCode": "SUN" },
  { "name": "Surigao", "stateCode": "SUN", "city": true },
  { "name": "Tagana-an", "stateCode": "SUN" },
  { "name": "Tubod", "stateCode": "SUN" },

  { "name": "Barobo", "stateCode": "SUR" },
  { "name": "Bayabas", "stateCode": "SUR" },
  { "name": "Bislig", "stateCode": "SUR", "city": true },
  { "name": "Cagwait", "stateCode": "SUR" },
  { "name": "Cantilan", "stateCode": "SUR" },
  { "name": "Carmen", "stateCode": "SUR" },
  { "name": "Carrascal", "stateCode": "SUR" },
  { "name": "Cortes", "stateCode": "SUR" },
  { "name": "Hinatuan", "stateCode": "SUR" },
  { "name": "Lanuza", "stateCode": "SUR" },
  { "name": "Lianga", "stateCode": "SUR" },
  { "name": "Lingig", "stateCode": "SUR" },
  { "name": "Madrid", "stateCode": "SUR" },
  { "name": "Marihatag", "stateCode": "SUR" },
  { "name": "San Agustin", "stateCode": "SUR" },
  { "name": "San Miguel", "stateCode": "SUR" },
  { "name": "Tagbina", "stateCode": "SUR" },
  { "name": "Tago", "stateCode": "SUR" },
  { "name": "Tandag", "stateCode": "SUR", "city": true },

  { "name": "Akbar", "stateCode": "BAS" },
  { "name": "Al-Barka", "stateCode": "BAS" },
  { "name": "Hadji Mohammad Ajul", "stateCode": "BAS" },
  { "name": "Hadji Muhtamad", "stateCode": "BAS" },
  { "name": "Isabela", "stateCode": "BAS", "city": true },
  { "name": "Lamitan", "stateCode": "BAS", "city": true },
  { "name": "Lantawan", "stateCode": "BAS" },
  { "name": "Maluso", "stateCode": "BAS" },
  { "name": "Sumisip", "stateCode": "BAS" },
  { "name": "Tabuan-Lasa", "stateCode": "BAS" },
  { "name": "Tipo-Tipo", "stateCode": "BAS" },
  { "name": "Tuburan", "stateCode": "BAS" },
  { "name": "Ungkaya Pukan", "stateCode": "BAS" },

  { "name": "Bacolod-Kalawi", "stateCode": "LAS" },
  { "name": "Balabagan", "stateCode": "LAS" },
  { "name": "Balindong", "stateCode": "LAS" },
  { "name": "Bayang", "stateCode": "LAS" },
  { "name": "Binidayan", "stateCode": "LAS" },
  { "name": "Buadiposo-Buntong", "stateCode": "LAS" },
  { "name": "Bubong", "stateCode": "LAS" },
  { "name": "Bumbaran", "stateCode": "LAS" },
  { "name": "Butig", "stateCode": "LAS" },
  { "name": "Calanogas", "stateCode": "LAS" },
  { "name": "Ditsaan-Ramain", "stateCode": "LAS" },
  { "name": "Ganassi", "stateCode": "LAS" },
  { "name": "Kapai", "stateCode": "LAS" },
  { "name": "Kapatagan", "stateCode": "LAS" },
  { "name": "Lumba-Bayabao", "stateCode": "LAS" },
  { "name": "Lumbaca-Unayan", "stateCode": "LAS" },
  { "name": "Lumbatan", "stateCode": "LAS" },
  { "name": "Lumbayanague", "stateCode": "LAS" },
  { "name": "Madalum", "stateCode": "LAS" },
  { "name": "Madamba", "stateCode": "LAS" },
  { "name": "Maguing", "stateCode": "LAS" },
  { "name": "Malabang", "stateCode": "LAS" },
  { "name": "Marantao", "stateCode": "LAS" },
  { "name": "Marawi", "stateCode": "LAS", "city": true },
  { "name": "Marogong", "stateCode": "LAS" },
  { "name": "Masiu", "stateCode": "LAS" },
  { "name": "Mulondo", "stateCode": "LAS" },
  { "name": "Pagayawan", "stateCode": "LAS" },
  { "name": "Piagapo", "stateCode": "LAS" },
  { "name": "Poona Bayabao", "stateCode": "LAS" },
  { "name": "Pualas", "stateCode": "LAS" },
  { "name": "Saguiaran", "stateCode": "LAS" },
  { "name": "Sultan Dumalondong", "stateCode": "LAS" },
  { "name": "Picong", "stateCode": "LAS" },
  { "name": "Tagoloan II", "stateCode": "LAS" },
  { "name": "Tamparan", "stateCode": "LAS" },
  { "name": "Taraka", "stateCode": "LAS" },
  { "name": "Tubaran", "stateCode": "LAS" },
  { "name": "Tugaya", "stateCode": "LAS" },
  { "name": "Wao", "stateCode": "LAS" },

  { "name": "Ampatuan", "stateCode": "MAG" },
  { "name": "Barira", "stateCode": "MAG" },
  { "name": "Buldon", "stateCode": "MAG" },
  { "name": "Buluan", "stateCode": "MAG" },
  { "name": "Cotabato", "stateCode": "MAG", "city": true },
  { "name": "Datu Abdullah Sangki", "stateCode": "MAG" },
  { "name": "Datu Anggal Midtimbang", "stateCode": "MAG" },
  { "name": "Datu Blah T. Sinsuat", "stateCode": "MAG" },
  { "name": "Datu Hoffer Ampatuan", "stateCode": "MAG" },
  { "name": "Datu Montawal", "stateCode": "MAG" },
  { "name": "Datu Odin Sinsuat", "stateCode": "MAG" },
  { "name": "Datu Paglas", "stateCode": "MAG" },
  { "name": "Datu Piang", "stateCode": "MAG" },
  { "name": "Datu Salibo", "stateCode": "MAG" },
  { "name": "Datu Saudi-Ampatuan", "stateCode": "MAG" },
  { "name": "Datu Unsay", "stateCode": "MAG" },
  { "name": "General Salipada K. Pendatun", "stateCode": "MAG" },
  { "name": "Guindulungan", "stateCode": "MAG" },
  { "name": "Kabuntalan", "stateCode": "MAG" },
  { "name": "Mamasapano", "stateCode": "MAG" },
  { "name": "Mangudadatu", "stateCode": "MAG" },
  { "name": "Matanog", "stateCode": "MAG" },
  { "name": "Northern Kabuntalan", "stateCode": "MAG" },
  { "name": "Pagalungan", "stateCode": "MAG" },
  { "name": "Paglat", "stateCode": "MAG" },
  { "name": "Pandag", "stateCode": "MAG" },
  { "name": "Parang", "stateCode": "MAG" },
  { "name": "Rajah Buayan", "stateCode": "MAG" },
  { "name": "Shariff Aguak", "stateCode": "MAG" },
  { "name": "Shariff Saydona Mustapha", "stateCode": "MAG" },
  { "name": "South Upi", "stateCode": "MAG" },
  { "name": "Sultan Kudarat", "stateCode": "MAG" },
  { "name": "Sultan Mastura", "stateCode": "MAG" },
  { "name": "Sultan sa Barongis", "stateCode": "MAG" },
  { "name": "Sultan Sumagka", "stateCode": "MAG" },
  { "name": "Talayan", "stateCode": "MAG" },
  { "name": "Upi", "stateCode": "MAG" },

  { "name": "Banguingui", "stateCode": "SLU" },
  { "name": "Hadji Panglima Tahil", "stateCode": "SLU" },
  { "name": "Indanan", "stateCode": "SLU" },
  { "name": "Jolo", "stateCode": "SLU" },
  { "name": "Kalingalan Caluang", "stateCode": "SLU" },
  { "name": "Lugus", "stateCode": "SLU" },
  { "name": "Luuk", "stateCode": "SLU" },
  { "name": "Maimbung", "stateCode": "SLU" },
  { "name": "Old Panamao", "stateCode": "SLU" },
  { "name": "Omar", "stateCode": "SLU" },
  { "name": "Pandami", "stateCode": "SLU" },
  { "name": "Panglima Estino", "stateCode": "SLU" },
  { "name": "Pangutaran", "stateCode": "SLU" },
  { "name": "Parang", "stateCode": "SLU" },
  { "name": "Pata", "stateCode": "SLU" },
  { "name": "Patikul", "stateCode": "SLU" },
  { "name": "Siasi", "stateCode": "SLU" },
  { "name": "Talipao", "stateCode": "SLU" },
  { "name": "Tapul", "stateCode": "SLU" },

  { "name": "Bongao", "stateCode": "TAW" },
  { "name": "Languyan", "stateCode": "TAW" },
  { "name": "Mapun", "stateCode": "TAW" },
  { "name": "Panglima Sugala", "stateCode": "TAW" },
  { "name": "Sapa-Sapa", "stateCode": "TAW" },
  { "name": "Sibutu", "stateCode": "TAW" },
  { "name": "Simunul", "stateCode": "TAW" },
  { "name": "Sitangkai", "stateCode": "TAW" },
  { "name": "South Ubian", "stateCode": "TAW" },
  { "name": "Tandubas", "stateCode": "TAW" },
  { "name": "Turtle Islands", "stateCode": "TAW" }
]
